/**
 * AI/LLM Triage Plugin
 *
 * AI and LLM Vulnerability Triage for stakeholder-specific decision making
 * Generated from YAML configuration.
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 * This file is auto-generated. To make changes:
 * 1. Edit the source YAML file: methodologies/ai_llm_triage.yaml
 * 2. Run: yarn generate-plugins
 *
 * @generated true
 * @source methodologies/ai_llm_triage.yaml
 * @generator scripts/generate-plugins.ts
 * @lastGenerated 2025-08-31T12:19:01.415Z
 */

export enum ExploitationStatus {
  NONE = "none",
  POC = "poc",
  ACTIVE = "active",
}

export enum StakeholderRole {
  DEPLOYER = "deployer",
  APPLICATION = "application",
  USER = "user",
}

export enum DeployerAttackVector {
  SUPPLY_CHAIN = "supply_chain",
  MODEL_POISONING = "model_poisoning",
  INFRASTRUCTURE_COMPROMISE = "infrastructure_compromise",
}

export enum ApplicationAttackVector {
  PROMPT_INJECTION = "prompt_injection",
  TOOL_MISUSE = "tool_misuse",
  PRIVILEGE_ESCALATION = "privilege_escalation",
  MEMORY_MANIPULATION = "memory_manipulation",
  ALIGNMENT_BYPASS = "alignment_bypass",
}

export enum UserAttackVector {
  DATA_EXTRACTION = "data_extraction",
  PROMPT_MANIPULATION = "prompt_manipulation",
  OUTPUT_MANIPULATION = "output_manipulation",
}

export enum ActionType {
  MONITOR = "MONITOR",
  ASSESS_RISK = "ASSESS_RISK",
  PROMPT_SANITIZATION = "PROMPT_SANITIZATION",
  FINETUNE_GUARDRAILS = "FINETUNE_GUARDRAILS",
  RETRAIN_MODEL = "RETRAIN_MODEL",
  HIGH_RISK = "HIGH_RISK",
  LOW_TRUST = "LOW_TRUST",
  IMMEDIATE_ACTION = "IMMEDIATE_ACTION",
}

export enum PriorityLevel {
  LOW = "LOW",
  MEDIUM = "MEDIUM",
  HIGH = "HIGH",
  IMMEDIATE = "IMMEDIATE",
}

export const priorityMap = {
  [ActionType.MONITOR]: PriorityLevel.LOW,
  [ActionType.ASSESS_RISK]: PriorityLevel.LOW,
  [ActionType.PROMPT_SANITIZATION]: PriorityLevel.MEDIUM,
  [ActionType.FINETUNE_GUARDRAILS]: PriorityLevel.MEDIUM,
  [ActionType.RETRAIN_MODEL]: PriorityLevel.HIGH,
  [ActionType.HIGH_RISK]: PriorityLevel.HIGH,
  [ActionType.LOW_TRUST]: PriorityLevel.MEDIUM,
  [ActionType.IMMEDIATE_ACTION]: PriorityLevel.IMMEDIATE,
};

export class OutcomeAiLlmTriage {
  priority: string;
  action: string;

  constructor(action: any) {
    this.priority = (priorityMap as any)[action];
    this.action = action;
  }
}

interface DecisionAiLlmTriageOptions {
  exploitation?: ExploitationStatus | string;
  stakeholderRole?: StakeholderRole | string;
  deployerAttackVector?: DeployerAttackVector | string;
  applicationAttackVector?: ApplicationAttackVector | string;
  userAttackVector?: UserAttackVector | string;
}

export class DecisionAiLlmTriage {
  exploitation?: ExploitationStatus;
  stakeholderRole?: StakeholderRole;
  deployerAttackVector?: DeployerAttackVector;
  applicationAttackVector?: ApplicationAttackVector;
  userAttackVector?: UserAttackVector;
  outcome?: OutcomeAiLlmTriage;

  constructor(options: DecisionAiLlmTriageOptions = {}) {
    if (typeof options.exploitation === "string") {
      this.exploitation =
        (Object.values(ExploitationStatus).find(
          (v) => v === options.exploitation,
        ) as ExploitationStatus) || undefined;
    } else {
      this.exploitation = options.exploitation;
    }
    if (typeof options.stakeholderRole === "string") {
      this.stakeholderRole =
        (Object.values(StakeholderRole).find(
          (v) => v === options.stakeholderRole,
        ) as StakeholderRole) || undefined;
    } else {
      this.stakeholderRole = options.stakeholderRole;
    }
    if (typeof options.deployerAttackVector === "string") {
      this.deployerAttackVector =
        (Object.values(DeployerAttackVector).find(
          (v) => v === options.deployerAttackVector,
        ) as DeployerAttackVector) || undefined;
    } else {
      this.deployerAttackVector = options.deployerAttackVector;
    }
    if (typeof options.applicationAttackVector === "string") {
      this.applicationAttackVector =
        (Object.values(ApplicationAttackVector).find(
          (v) => v === options.applicationAttackVector,
        ) as ApplicationAttackVector) || undefined;
    } else {
      this.applicationAttackVector = options.applicationAttackVector;
    }
    if (typeof options.userAttackVector === "string") {
      this.userAttackVector =
        (Object.values(UserAttackVector).find(
          (v) => v === options.userAttackVector,
        ) as UserAttackVector) || undefined;
    } else {
      this.userAttackVector = options.userAttackVector;
    }

    // Always try to evaluate if we have the minimum required parameters
    if (
      this.exploitation !== undefined &&
      this.stakeholderRole !== undefined &&
      this.deployerAttackVector !== undefined &&
      this.applicationAttackVector !== undefined &&
      this.userAttackVector !== undefined
    ) {
      this.outcome = this.evaluate();
    }
  }

  evaluate(): OutcomeAiLlmTriage {
    const action = this.traverseTree();
    this.outcome = new OutcomeAiLlmTriage(action);
    return this.outcome;
  }

  toVector(): string {
    if (!this.outcome) {
      this.evaluate();
    }

    const exploitationVector =
      { NONE: "N", POC: "P", ACTIVE: "A" }[
        this.exploitation?.toString?.()?.toUpperCase?.() ?? ""
      ] ||
      this.exploitation ||
      "";
    const stakeholder_roleVector =
      { DEPLOYER: "D", APPLICATION: "A", USER: "U" }[
        this.stakeholderRole?.toString?.()?.toUpperCase?.() ?? ""
      ] ||
      this.stakeholderRole ||
      "";
    const deployer_attack_vectorVector =
      {
        SUPPLY_CHAIN: "SC",
        MODEL_POISONING: "MP",
        INFRASTRUCTURE_COMPROMISE: "IC",
      }[this.deployerAttackVector?.toString?.()?.toUpperCase?.() ?? ""] ||
      this.deployerAttackVector ||
      "";
    const application_attack_vectorVector =
      {
        PROMPT_INJECTION: "PI",
        TOOL_MISUSE: "TM",
        PRIVILEGE_ESCALATION: "PE",
        MEMORY_MANIPULATION: "MM",
        ALIGNMENT_BYPASS: "AB",
      }[this.applicationAttackVector?.toString?.()?.toUpperCase?.() ?? ""] ||
      this.applicationAttackVector ||
      "";
    const user_attack_vectorVector =
      {
        DATA_EXTRACTION: "DE",
        PROMPT_MANIPULATION: "PM",
        OUTPUT_MANIPULATION: "OM",
      }[this.userAttackVector?.toString?.()?.toUpperCase?.() ?? ""] ||
      this.userAttackVector ||
      "";
    const timestamp = new Date().toISOString();
    return `AI_LLMv2/E:${exploitationVector}/SR:${stakeholder_roleVector}/DAV:${deployer_attack_vectorVector}/AAV:${application_attack_vectorVector}/UAV:${user_attack_vectorVector}/${timestamp}/`;
  }

  static fromVector(vectorString: string): DecisionAiLlmTriage {
    const regex = /^AI_LLMv2\/(.+)\/([0-9T:\-\.Z]+)\/?$/;
    const match = vectorString.match(regex);

    if (!match) {
      throw new Error(
        `Invalid vector string format for AI/LLM Triage: ${vectorString}`,
      );
    }

    const paramsString = match[1];
    const params = new Map<string, string>();

    const paramPairs = paramsString.split("/");
    for (const pair of paramPairs) {
      const [key, value] = pair.split(":");
      if (key && value !== undefined) {
        params.set(key, value);
      }
    }

    const exploitationMatch = params.get("E");
    const stakeholder_roleMatch = params.get("SR");
    const deployer_attack_vectorMatch = params.get("DAV");
    const application_attack_vectorMatch = params.get("AAV");
    const user_attack_vectorMatch = params.get("UAV");

    return new DecisionAiLlmTriage({
      exploitation:
        { N: "NONE", P: "POC", A: "ACTIVE" }[exploitationMatch || ""] ||
        exploitationMatch,
      stakeholderRole:
        { D: "DEPLOYER", A: "APPLICATION", U: "USER" }[
          stakeholder_roleMatch || ""
        ] || stakeholder_roleMatch,
      deployerAttackVector:
        {
          SC: "SUPPLY_CHAIN",
          MP: "MODEL_POISONING",
          IC: "INFRASTRUCTURE_COMPROMISE",
        }[deployer_attack_vectorMatch || ""] || deployer_attack_vectorMatch,
      applicationAttackVector:
        {
          PI: "PROMPT_INJECTION",
          TM: "TOOL_MISUSE",
          PE: "PRIVILEGE_ESCALATION",
          MM: "MEMORY_MANIPULATION",
          AB: "ALIGNMENT_BYPASS",
        }[application_attack_vectorMatch || ""] ||
        application_attack_vectorMatch,
      userAttackVector:
        {
          DE: "DATA_EXTRACTION",
          PM: "PROMPT_MANIPULATION",
          OM: "OUTPUT_MANIPULATION",
        }[user_attack_vectorMatch || ""] || user_attack_vectorMatch,
    });
  }

  private traverseTree(): any {
    // Traverse the decision tree to determine the outcome
    if (this.exploitation === ExploitationStatus.NONE) {
      if (this.stakeholderRole === StakeholderRole.DEPLOYER) {
        if (this.deployerAttackVector === DeployerAttackVector.SUPPLY_CHAIN) {
          return ActionType.ASSESS_RISK;
        } else if (
          this.deployerAttackVector === DeployerAttackVector.MODEL_POISONING
        ) {
          return ActionType.ASSESS_RISK;
        } else if (
          this.deployerAttackVector ===
          DeployerAttackVector.INFRASTRUCTURE_COMPROMISE
        ) {
          return ActionType.MONITOR;
        }
      } else if (this.stakeholderRole === StakeholderRole.APPLICATION) {
        if (
          this.applicationAttackVector ===
          ApplicationAttackVector.PROMPT_INJECTION
        ) {
          return ActionType.MONITOR;
        } else if (
          this.applicationAttackVector === ApplicationAttackVector.TOOL_MISUSE
        ) {
          return ActionType.PROMPT_SANITIZATION;
        } else if (
          this.applicationAttackVector ===
          ApplicationAttackVector.PRIVILEGE_ESCALATION
        ) {
          return ActionType.FINETUNE_GUARDRAILS;
        } else if (
          this.applicationAttackVector ===
          ApplicationAttackVector.MEMORY_MANIPULATION
        ) {
          return ActionType.MONITOR;
        } else if (
          this.applicationAttackVector ===
          ApplicationAttackVector.ALIGNMENT_BYPASS
        ) {
          return ActionType.MONITOR;
        }
      } else if (this.stakeholderRole === StakeholderRole.USER) {
        if (this.userAttackVector === UserAttackVector.DATA_EXTRACTION) {
          return ActionType.ASSESS_RISK;
        } else if (
          this.userAttackVector === UserAttackVector.PROMPT_MANIPULATION
        ) {
          return ActionType.LOW_TRUST;
        } else if (
          this.userAttackVector === UserAttackVector.OUTPUT_MANIPULATION
        ) {
          return ActionType.LOW_TRUST;
        }
      }
    } else if (this.exploitation === ExploitationStatus.POC) {
      if (this.stakeholderRole === StakeholderRole.DEPLOYER) {
        if (this.deployerAttackVector === DeployerAttackVector.SUPPLY_CHAIN) {
          return ActionType.FINETUNE_GUARDRAILS;
        } else if (
          this.deployerAttackVector === DeployerAttackVector.MODEL_POISONING
        ) {
          return ActionType.RETRAIN_MODEL;
        } else if (
          this.deployerAttackVector ===
          DeployerAttackVector.INFRASTRUCTURE_COMPROMISE
        ) {
          return ActionType.ASSESS_RISK;
        }
      } else if (this.stakeholderRole === StakeholderRole.APPLICATION) {
        if (
          this.applicationAttackVector ===
          ApplicationAttackVector.PROMPT_INJECTION
        ) {
          return ActionType.PROMPT_SANITIZATION;
        } else if (
          this.applicationAttackVector === ApplicationAttackVector.TOOL_MISUSE
        ) {
          return ActionType.FINETUNE_GUARDRAILS;
        } else if (
          this.applicationAttackVector ===
          ApplicationAttackVector.PRIVILEGE_ESCALATION
        ) {
          return ActionType.RETRAIN_MODEL;
        } else if (
          this.applicationAttackVector ===
          ApplicationAttackVector.MEMORY_MANIPULATION
        ) {
          return ActionType.FINETUNE_GUARDRAILS;
        } else if (
          this.applicationAttackVector ===
          ApplicationAttackVector.ALIGNMENT_BYPASS
        ) {
          return ActionType.PROMPT_SANITIZATION;
        }
      } else if (this.stakeholderRole === StakeholderRole.USER) {
        if (this.userAttackVector === UserAttackVector.DATA_EXTRACTION) {
          return ActionType.FINETUNE_GUARDRAILS;
        } else if (
          this.userAttackVector === UserAttackVector.PROMPT_MANIPULATION
        ) {
          return ActionType.HIGH_RISK;
        } else if (
          this.userAttackVector === UserAttackVector.OUTPUT_MANIPULATION
        ) {
          return ActionType.HIGH_RISK;
        }
      }
    } else if (this.exploitation === ExploitationStatus.ACTIVE) {
      if (this.stakeholderRole === StakeholderRole.DEPLOYER) {
        if (this.deployerAttackVector === DeployerAttackVector.SUPPLY_CHAIN) {
          return ActionType.IMMEDIATE_ACTION;
        } else if (
          this.deployerAttackVector === DeployerAttackVector.MODEL_POISONING
        ) {
          return ActionType.IMMEDIATE_ACTION;
        } else if (
          this.deployerAttackVector ===
          DeployerAttackVector.INFRASTRUCTURE_COMPROMISE
        ) {
          return ActionType.RETRAIN_MODEL;
        }
      } else if (this.stakeholderRole === StakeholderRole.APPLICATION) {
        if (
          this.applicationAttackVector ===
          ApplicationAttackVector.PROMPT_INJECTION
        ) {
          return ActionType.FINETUNE_GUARDRAILS;
        } else if (
          this.applicationAttackVector === ApplicationAttackVector.TOOL_MISUSE
        ) {
          return ActionType.RETRAIN_MODEL;
        } else if (
          this.applicationAttackVector ===
          ApplicationAttackVector.PRIVILEGE_ESCALATION
        ) {
          return ActionType.IMMEDIATE_ACTION;
        } else if (
          this.applicationAttackVector ===
          ApplicationAttackVector.MEMORY_MANIPULATION
        ) {
          return ActionType.RETRAIN_MODEL;
        } else if (
          this.applicationAttackVector ===
          ApplicationAttackVector.ALIGNMENT_BYPASS
        ) {
          return ActionType.FINETUNE_GUARDRAILS;
        }
      } else if (this.stakeholderRole === StakeholderRole.USER) {
        if (this.userAttackVector === UserAttackVector.DATA_EXTRACTION) {
          return ActionType.IMMEDIATE_ACTION;
        } else if (
          this.userAttackVector === UserAttackVector.PROMPT_MANIPULATION
        ) {
          return ActionType.IMMEDIATE_ACTION;
        } else if (
          this.userAttackVector === UserAttackVector.OUTPUT_MANIPULATION
        ) {
          return ActionType.IMMEDIATE_ACTION;
        }
      }
    }

    // Default action for unmapped paths
    return ActionType.MONITOR;
  }
}
