/**
 * CISA Plugin
 * 
 * CISA Stakeholder-Specific Vulnerability Categorization
 * Generated from YAML configuration.
 * 
 * DO NOT EDIT THIS FILE DIRECTLY
 * This file is auto-generated. To make changes:
 * 1. Edit the source YAML file: methodologies/cisa.yaml
 * 2. Run: yarn generate-plugins
 * 
 * @generated true
 * @source methodologies/cisa.yaml
 * @generator scripts/generate-plugins.ts
 * @lastGenerated 2025-08-29T10:52:45.995Z
 */

export enum ExploitationStatus {
  NONE = "none",
  POC = "poc",
  ACTIVE = "active"
}

export enum AutomatableStatus {
  YES = "yes",
  NO = "no"
}

export enum TechnicalImpactLevel {
  PARTIAL = "partial",
  TOTAL = "total"
}

export enum MissionWellbeingImpactLevel {
  LOW = "low",
  MEDIUM = "medium",
  HIGH = "high"
}

export enum ActionType {
  TRACK = 'TRACK',
  TRACK_STAR = 'TRACK_STAR',
  ATTEND = 'ATTEND',
  ACT = 'ACT'
}

export enum PriorityLevel {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  IMMEDIATE = 'IMMEDIATE'
}

export const priorityMap = {
  [ActionType.TRACK]: PriorityLevel.LOW,
  [ActionType.TRACK_STAR]: PriorityLevel.MEDIUM,
  [ActionType.ATTEND]: PriorityLevel.MEDIUM,
  [ActionType.ACT]: PriorityLevel.IMMEDIATE
};

export class OutcomeCisa {
  priority: string;
  action: string;

  constructor(action: any) {
    this.priority = (priorityMap as any)[action];
    this.action = action;
  }
}

interface DecisionCisaOptions {
  exploitation?: ExploitationStatus | string;
  automatable?: AutomatableStatus | string;
  technicalImpact?: TechnicalImpactLevel | string;
  missionWellbeingImpact?: MissionWellbeingImpactLevel | string;
}

export class DecisionCisa {
  exploitation?: ExploitationStatus;
  automatable?: AutomatableStatus;
  technicalImpact?: TechnicalImpactLevel;
  missionWellbeingImpact?: MissionWellbeingImpactLevel;
  outcome?: OutcomeCisa;

  constructor(options: DecisionCisaOptions = {}) {
    if (typeof options.exploitation === 'string') {
      this.exploitation = Object.values(ExploitationStatus).find(v => v === options.exploitation) as ExploitationStatus || undefined;
    } else {
      this.exploitation = options.exploitation;
    }
    if (typeof options.automatable === 'string') {
      this.automatable = Object.values(AutomatableStatus).find(v => v === options.automatable) as AutomatableStatus || undefined;
    } else {
      this.automatable = options.automatable;
    }
    if (typeof options.technicalImpact === 'string') {
      this.technicalImpact = Object.values(TechnicalImpactLevel).find(v => v === options.technicalImpact) as TechnicalImpactLevel || undefined;
    } else {
      this.technicalImpact = options.technicalImpact;
    }
    if (typeof options.missionWellbeingImpact === 'string') {
      this.missionWellbeingImpact = Object.values(MissionWellbeingImpactLevel).find(v => v === options.missionWellbeingImpact) as MissionWellbeingImpactLevel || undefined;
    } else {
      this.missionWellbeingImpact = options.missionWellbeingImpact;
    }
    
    // Always try to evaluate if we have the minimum required parameters
    if (this.exploitation !== undefined && this.automatable !== undefined && this.technicalImpact !== undefined && this.missionWellbeingImpact !== undefined) {
      this.outcome = this.evaluate();
    }
  }

  evaluate(): OutcomeCisa {
    const action = this.traverseTree();
    this.outcome = new OutcomeCisa(action);
    return this.outcome;
  }

  toVector(): string {
    if (!this.outcome) {
      this.evaluate();
    }

    const exploitationVector = {"NONE":"N","POC":"P","ACTIVE":"A"}[this.exploitation?.toString?.()?.toUpperCase?.() ?? ''] || this.exploitation || '';
    const automatableVector = {"YES":"Y","NO":"N"}[this.automatable?.toString?.()?.toUpperCase?.() ?? ''] || this.automatable || '';
    const technical_impactVector = {"PARTIAL":"P","TOTAL":"T"}[this.technicalImpact?.toString?.()?.toUpperCase?.() ?? ''] || this.technicalImpact || '';
    const mission_wellbeingVector = {"LOW":"L","MEDIUM":"M","HIGH":"H"}[this.missionWellbeingImpact?.toString?.()?.toUpperCase?.() ?? ''] || this.missionWellbeingImpact || '';
    const timestamp = new Date().toISOString();
    return `CISAv1/E:${exploitationVector}/A:${automatableVector}/T:${technical_impactVector}/M:${mission_wellbeingVector}/${timestamp}/`;
  }

  static fromVector(vectorString: string): DecisionCisa {
    const regex = /^CISAv1\/(.+)\/([0-9T:\-\.Z]+)\/?$/;
    const match = vectorString.match(regex);

    if (!match) {
      throw new Error(`Invalid vector string format for CISA: ${vectorString}`);
    }

    const paramsString = match[1];
    const params = new Map<string, string>();

    const paramPairs = paramsString.split('/');
    for (const pair of paramPairs) {
      const [key, value] = pair.split(':');
      if (key && value !== undefined) {
        params.set(key, value);
      }
    }

    const exploitationMatch = params.get('E');
    const automatableMatch = params.get('A');
    const technical_impactMatch = params.get('T');
    const mission_wellbeingMatch = params.get('M');

    return new DecisionCisa({
      exploitation: {"N":"NONE","P":"POC","A":"ACTIVE"}[exploitationMatch || ''] || exploitationMatch,
      automatable: {"Y":"YES","N":"NO"}[automatableMatch || ''] || automatableMatch,
      technicalImpact: {"P":"PARTIAL","T":"TOTAL"}[technical_impactMatch || ''] || technical_impactMatch,
      missionWellbeingImpact: {"L":"LOW","M":"MEDIUM","H":"HIGH"}[mission_wellbeingMatch || ''] || mission_wellbeingMatch,
    });
  }

  private traverseTree(): any {
    // Traverse the decision tree to determine the outcome
    if (this.exploitation === ExploitationStatus.NONE) {
      if (this.automatable === AutomatableStatus.YES) {
        if (this.technicalImpact === TechnicalImpactLevel.PARTIAL) {
          if (this.missionWellbeingImpact === MissionWellbeingImpactLevel.HIGH) {
            return ActionType.ATTEND;
          }
        }
        else if (this.technicalImpact === TechnicalImpactLevel.TOTAL) {
          if (this.missionWellbeingImpact === MissionWellbeingImpactLevel.HIGH) {
            return ActionType.ATTEND;
          }
        }
      }
      else if (this.automatable === AutomatableStatus.NO) {
        if (this.technicalImpact === TechnicalImpactLevel.PARTIAL) {
          if (this.missionWellbeingImpact === MissionWellbeingImpactLevel.HIGH) {
            return ActionType.TRACK_STAR;
          }
        }
        else if (this.technicalImpact === TechnicalImpactLevel.TOTAL) {
          if (this.missionWellbeingImpact === MissionWellbeingImpactLevel.HIGH) {
            return ActionType.TRACK_STAR;
          }
        }
      }
    }
    else if (this.exploitation === ExploitationStatus.POC) {
      if (this.automatable === AutomatableStatus.YES) {
        if (this.technicalImpact === TechnicalImpactLevel.TOTAL) {
          if (this.missionWellbeingImpact === MissionWellbeingImpactLevel.MEDIUM) {
            return ActionType.TRACK_STAR;
          }
          else if (this.missionWellbeingImpact === MissionWellbeingImpactLevel.HIGH) {
            return ActionType.ATTEND;
          }
        }
        else if (this.technicalImpact === TechnicalImpactLevel.PARTIAL) {
          if (this.missionWellbeingImpact === MissionWellbeingImpactLevel.HIGH) {
            return ActionType.ATTEND;
          }
        }
      }
      else if (this.automatable === AutomatableStatus.NO) {
        if (this.technicalImpact === TechnicalImpactLevel.PARTIAL) {
          if (this.missionWellbeingImpact === MissionWellbeingImpactLevel.HIGH) {
            return ActionType.TRACK_STAR;
          }
        }
        else if (this.technicalImpact === TechnicalImpactLevel.TOTAL) {
          if (this.missionWellbeingImpact === MissionWellbeingImpactLevel.MEDIUM) {
            return ActionType.TRACK_STAR;
          }
          else if (this.missionWellbeingImpact === MissionWellbeingImpactLevel.HIGH) {
            return ActionType.ATTEND;
          }
        }
      }
    }
    else if (this.exploitation === ExploitationStatus.ACTIVE) {
      if (this.automatable === AutomatableStatus.YES) {
        if (this.technicalImpact === TechnicalImpactLevel.PARTIAL) {
          if (this.missionWellbeingImpact === MissionWellbeingImpactLevel.LOW) {
            return ActionType.ATTEND;
          }
          else if (this.missionWellbeingImpact === MissionWellbeingImpactLevel.MEDIUM) {
            return ActionType.ATTEND;
          }
          else if (this.missionWellbeingImpact === MissionWellbeingImpactLevel.HIGH) {
            return ActionType.ACT;
          }
        }
        else if (this.technicalImpact === TechnicalImpactLevel.TOTAL) {
          if (this.missionWellbeingImpact === MissionWellbeingImpactLevel.LOW) {
            return ActionType.ATTEND;
          }
          else if (this.missionWellbeingImpact === MissionWellbeingImpactLevel.MEDIUM) {
            return ActionType.ACT;
          }
          else if (this.missionWellbeingImpact === MissionWellbeingImpactLevel.HIGH) {
            return ActionType.ACT;
          }
        }
      }
      else if (this.automatable === AutomatableStatus.NO) {
        if (this.technicalImpact === TechnicalImpactLevel.PARTIAL) {
          if (this.missionWellbeingImpact === MissionWellbeingImpactLevel.HIGH) {
            return ActionType.ATTEND;
          }
        }
        else if (this.technicalImpact === TechnicalImpactLevel.TOTAL) {
          if (this.missionWellbeingImpact === MissionWellbeingImpactLevel.MEDIUM) {
            return ActionType.ATTEND;
          }
          else if (this.missionWellbeingImpact === MissionWellbeingImpactLevel.HIGH) {
            return ActionType.ACT;
          }
        }
      }
    }
    
    // Default action for unmapped paths
    return ActionType.TRACK;
  }
}
