/**
 * Coordinator Triage Plugin
 *
 * CERT/CC Coordinator Triage Decision Model
 * Generated from YAML configuration.
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 * This file is auto-generated. To make changes:
 * 1. Edit the source YAML file: methodologies/coordinator_triage.yaml
 * 2. Run: yarn generate-plugins
 *
 * @generated true
 * @source methodologies/coordinator_triage.yaml
 * @generator scripts/generate-plugins.ts
 * @lastGenerated 2025-08-29T14:35:41.672Z
 */

export enum ReportPublicStatus {
  YES = "yes",
  NO = "no",
}

export enum SupplierContactedStatus {
  YES = "yes",
  NO = "no",
}

export enum ReportCredibilityLevel {
  CREDIBLE = "credible",
  NOT_CREDIBLE = "not_credible",
}

export enum SupplierCardinalityLevel {
  ONE = "one",
  MULTIPLE = "multiple",
}

export enum UtilityLevel {
  LABORIOUS = "laborious",
  EFFICIENT = "efficient",
  SUPER_EFFECTIVE = "super_effective",
}

export enum PublicSafetyImpactLevel {
  MINIMAL = "minimal",
  SIGNIFICANT = "significant",
}

export enum ActionType {
  DECLINE = "DECLINE",
  TRACK = "TRACK",
  COORDINATE = "COORDINATE",
}

export enum PriorityLevel {
  LOW = "LOW",
  MEDIUM = "MEDIUM",
  HIGH = "HIGH",
}

export const priorityMap = {
  [ActionType.DECLINE]: PriorityLevel.LOW,
  [ActionType.TRACK]: PriorityLevel.MEDIUM,
  [ActionType.COORDINATE]: PriorityLevel.HIGH,
};

export class OutcomeCoordinatorTriage {
  priority: string;
  action: string;

  constructor(action: any) {
    this.priority = (priorityMap as any)[action];
    this.action = action;
  }
}

interface DecisionCoordinatorTriageOptions {
  reportPublic?: ReportPublicStatus | string;
  supplierContacted?: SupplierContactedStatus | string;
  reportCredibility?: ReportCredibilityLevel | string;
  supplierCardinality?: SupplierCardinalityLevel | string;
  utility?: UtilityLevel | string;
  publicSafetyImpact?: PublicSafetyImpactLevel | string;
}

export class DecisionCoordinatorTriage {
  reportPublic?: ReportPublicStatus;
  supplierContacted?: SupplierContactedStatus;
  reportCredibility?: ReportCredibilityLevel;
  supplierCardinality?: SupplierCardinalityLevel;
  utility?: UtilityLevel;
  publicSafetyImpact?: PublicSafetyImpactLevel;
  outcome?: OutcomeCoordinatorTriage;

  constructor(options: DecisionCoordinatorTriageOptions = {}) {
    if (typeof options.reportPublic === "string") {
      this.reportPublic =
        (Object.values(ReportPublicStatus).find(
          (v) => v === options.reportPublic,
        ) as ReportPublicStatus) || undefined;
    } else {
      this.reportPublic = options.reportPublic;
    }
    if (typeof options.supplierContacted === "string") {
      this.supplierContacted =
        (Object.values(SupplierContactedStatus).find(
          (v) => v === options.supplierContacted,
        ) as SupplierContactedStatus) || undefined;
    } else {
      this.supplierContacted = options.supplierContacted;
    }
    if (typeof options.reportCredibility === "string") {
      this.reportCredibility =
        (Object.values(ReportCredibilityLevel).find(
          (v) => v === options.reportCredibility,
        ) as ReportCredibilityLevel) || undefined;
    } else {
      this.reportCredibility = options.reportCredibility;
    }
    if (typeof options.supplierCardinality === "string") {
      this.supplierCardinality =
        (Object.values(SupplierCardinalityLevel).find(
          (v) => v === options.supplierCardinality,
        ) as SupplierCardinalityLevel) || undefined;
    } else {
      this.supplierCardinality = options.supplierCardinality;
    }
    if (typeof options.utility === "string") {
      this.utility =
        (Object.values(UtilityLevel).find(
          (v) => v === options.utility,
        ) as UtilityLevel) || undefined;
    } else {
      this.utility = options.utility;
    }
    if (typeof options.publicSafetyImpact === "string") {
      this.publicSafetyImpact =
        (Object.values(PublicSafetyImpactLevel).find(
          (v) => v === options.publicSafetyImpact,
        ) as PublicSafetyImpactLevel) || undefined;
    } else {
      this.publicSafetyImpact = options.publicSafetyImpact;
    }

    // Always try to evaluate if we have the minimum required parameters
    if (
      this.reportPublic !== undefined &&
      this.supplierContacted !== undefined &&
      this.reportCredibility !== undefined &&
      this.supplierCardinality !== undefined &&
      this.utility !== undefined &&
      this.publicSafetyImpact !== undefined
    ) {
      this.outcome = this.evaluate();
    }
  }

  evaluate(): OutcomeCoordinatorTriage {
    const action = this.traverseTree();
    this.outcome = new OutcomeCoordinatorTriage(action);
    return this.outcome;
  }

  toVector(): string {
    if (!this.outcome) {
      this.evaluate();
    }

    const report_publicVector =
      { YES: "Y", NO: "N" }[
        this.reportPublic?.toString?.()?.toUpperCase?.() ?? ""
      ] ||
      this.reportPublic ||
      "";
    const supplier_contactedVector =
      { YES: "Y", NO: "N" }[
        this.supplierContacted?.toString?.()?.toUpperCase?.() ?? ""
      ] ||
      this.supplierContacted ||
      "";
    const report_credibilityVector =
      { CREDIBLE: "C", NOT_CREDIBLE: "N" }[
        this.reportCredibility?.toString?.()?.toUpperCase?.() ?? ""
      ] ||
      this.reportCredibility ||
      "";
    const supplier_cardinalityVector =
      { ONE: "O", MULTIPLE: "M" }[
        this.supplierCardinality?.toString?.()?.toUpperCase?.() ?? ""
      ] ||
      this.supplierCardinality ||
      "";
    const utilityVector =
      { LABORIOUS: "L", EFFICIENT: "E", SUPER_EFFECTIVE: "S" }[
        this.utility?.toString?.()?.toUpperCase?.() ?? ""
      ] ||
      this.utility ||
      "";
    const public_safetyVector =
      { MINIMAL: "M", SIGNIFICANT: "S" }[
        this.publicSafetyImpact?.toString?.()?.toUpperCase?.() ?? ""
      ] ||
      this.publicSafetyImpact ||
      "";
    const timestamp = new Date().toISOString();
    return `COORD_TRIAGEv1/RP:${report_publicVector}/SC:${supplier_contactedVector}/RC:${report_credibilityVector}/CA:${supplier_cardinalityVector}/U:${utilityVector}/PS:${public_safetyVector}/${timestamp}/`;
  }

  static fromVector(vectorString: string): DecisionCoordinatorTriage {
    const regex = /^COORD_TRIAGEv1\/(.+)\/([0-9T:\-\.Z]+)\/?$/;
    const match = vectorString.match(regex);

    if (!match) {
      throw new Error(
        `Invalid vector string format for Coordinator Triage: ${vectorString}`,
      );
    }

    const paramsString = match[1];
    const params = new Map<string, string>();

    const paramPairs = paramsString.split("/");
    for (const pair of paramPairs) {
      const [key, value] = pair.split(":");
      if (key && value !== undefined) {
        params.set(key, value);
      }
    }

    const report_publicMatch = params.get("RP");
    const supplier_contactedMatch = params.get("SC");
    const report_credibilityMatch = params.get("RC");
    const supplier_cardinalityMatch = params.get("CA");
    const utilityMatch = params.get("U");
    const public_safetyMatch = params.get("PS");

    return new DecisionCoordinatorTriage({
      reportPublic:
        { Y: "YES", N: "NO" }[report_publicMatch || ""] || report_publicMatch,
      supplierContacted:
        { Y: "YES", N: "NO" }[supplier_contactedMatch || ""] ||
        supplier_contactedMatch,
      reportCredibility:
        { C: "CREDIBLE", N: "NOT_CREDIBLE" }[report_credibilityMatch || ""] ||
        report_credibilityMatch,
      supplierCardinality:
        { O: "ONE", M: "MULTIPLE" }[supplier_cardinalityMatch || ""] ||
        supplier_cardinalityMatch,
      utility:
        { L: "LABORIOUS", E: "EFFICIENT", S: "SUPER_EFFECTIVE" }[
          utilityMatch || ""
        ] || utilityMatch,
      publicSafetyImpact:
        { M: "MINIMAL", S: "SIGNIFICANT" }[public_safetyMatch || ""] ||
        public_safetyMatch,
    });
  }

  private traverseTree(): any {
    // Traverse the decision tree to determine the outcome
    if (this.reportPublic === ReportPublicStatus.YES) {
      if (this.supplierContacted === SupplierContactedStatus.YES) {
        if (this.reportCredibility === ReportCredibilityLevel.CREDIBLE) {
          if (this.supplierCardinality === SupplierCardinalityLevel.MULTIPLE) {
            if (this.utility === UtilityLevel.SUPER_EFFECTIVE) {
              if (
                this.publicSafetyImpact === PublicSafetyImpactLevel.SIGNIFICANT
              ) {
                return ActionType.COORDINATE;
              } else if (
                this.publicSafetyImpact === PublicSafetyImpactLevel.MINIMAL
              ) {
                return ActionType.TRACK;
              }
            } else if (this.utility === UtilityLevel.EFFICIENT) {
              if (
                this.publicSafetyImpact === PublicSafetyImpactLevel.SIGNIFICANT
              ) {
                return ActionType.TRACK;
              } else if (
                this.publicSafetyImpact === PublicSafetyImpactLevel.MINIMAL
              ) {
                return ActionType.DECLINE;
              }
            } else if (this.utility === UtilityLevel.LABORIOUS) {
              if (
                this.publicSafetyImpact === PublicSafetyImpactLevel.SIGNIFICANT
              ) {
                return ActionType.DECLINE;
              } else if (
                this.publicSafetyImpact === PublicSafetyImpactLevel.MINIMAL
              ) {
                return ActionType.DECLINE;
              }
            }
          } else if (
            this.supplierCardinality === SupplierCardinalityLevel.ONE
          ) {
            if (this.utility === UtilityLevel.SUPER_EFFECTIVE) {
              if (
                this.publicSafetyImpact === PublicSafetyImpactLevel.SIGNIFICANT
              ) {
                return ActionType.TRACK;
              } else if (
                this.publicSafetyImpact === PublicSafetyImpactLevel.MINIMAL
              ) {
                return ActionType.DECLINE;
              }
            } else if (this.utility === UtilityLevel.EFFICIENT) {
              if (
                this.publicSafetyImpact === PublicSafetyImpactLevel.SIGNIFICANT
              ) {
                return ActionType.DECLINE;
              } else if (
                this.publicSafetyImpact === PublicSafetyImpactLevel.MINIMAL
              ) {
                return ActionType.DECLINE;
              }
            } else if (this.utility === UtilityLevel.LABORIOUS) {
              if (
                this.publicSafetyImpact === PublicSafetyImpactLevel.SIGNIFICANT
              ) {
                return ActionType.DECLINE;
              } else if (
                this.publicSafetyImpact === PublicSafetyImpactLevel.MINIMAL
              ) {
                return ActionType.DECLINE;
              }
            }
          }
        } else if (
          this.reportCredibility === ReportCredibilityLevel.NOT_CREDIBLE
        ) {
          if (this.supplierCardinality === SupplierCardinalityLevel.MULTIPLE) {
            if (this.utility === UtilityLevel.SUPER_EFFECTIVE) {
              if (
                this.publicSafetyImpact === PublicSafetyImpactLevel.SIGNIFICANT
              ) {
                return ActionType.DECLINE;
              } else if (
                this.publicSafetyImpact === PublicSafetyImpactLevel.MINIMAL
              ) {
                return ActionType.DECLINE;
              }
            } else if (this.utility === UtilityLevel.EFFICIENT) {
              if (
                this.publicSafetyImpact === PublicSafetyImpactLevel.SIGNIFICANT
              ) {
                return ActionType.DECLINE;
              } else if (
                this.publicSafetyImpact === PublicSafetyImpactLevel.MINIMAL
              ) {
                return ActionType.DECLINE;
              }
            } else if (this.utility === UtilityLevel.LABORIOUS) {
              if (
                this.publicSafetyImpact === PublicSafetyImpactLevel.SIGNIFICANT
              ) {
                return ActionType.DECLINE;
              } else if (
                this.publicSafetyImpact === PublicSafetyImpactLevel.MINIMAL
              ) {
                return ActionType.DECLINE;
              }
            }
          } else if (
            this.supplierCardinality === SupplierCardinalityLevel.ONE
          ) {
            if (this.utility === UtilityLevel.SUPER_EFFECTIVE) {
              if (
                this.publicSafetyImpact === PublicSafetyImpactLevel.SIGNIFICANT
              ) {
                return ActionType.DECLINE;
              } else if (
                this.publicSafetyImpact === PublicSafetyImpactLevel.MINIMAL
              ) {
                return ActionType.DECLINE;
              }
            } else if (this.utility === UtilityLevel.EFFICIENT) {
              if (
                this.publicSafetyImpact === PublicSafetyImpactLevel.SIGNIFICANT
              ) {
                return ActionType.DECLINE;
              } else if (
                this.publicSafetyImpact === PublicSafetyImpactLevel.MINIMAL
              ) {
                return ActionType.DECLINE;
              }
            } else if (this.utility === UtilityLevel.LABORIOUS) {
              if (
                this.publicSafetyImpact === PublicSafetyImpactLevel.SIGNIFICANT
              ) {
                return ActionType.DECLINE;
              } else if (
                this.publicSafetyImpact === PublicSafetyImpactLevel.MINIMAL
              ) {
                return ActionType.DECLINE;
              }
            }
          }
        }
      } else if (this.supplierContacted === SupplierContactedStatus.NO) {
        if (this.reportCredibility === ReportCredibilityLevel.CREDIBLE) {
          if (this.supplierCardinality === SupplierCardinalityLevel.MULTIPLE) {
            if (this.utility === UtilityLevel.SUPER_EFFECTIVE) {
              if (
                this.publicSafetyImpact === PublicSafetyImpactLevel.SIGNIFICANT
              ) {
                return ActionType.COORDINATE;
              } else if (
                this.publicSafetyImpact === PublicSafetyImpactLevel.MINIMAL
              ) {
                return ActionType.TRACK;
              }
            } else if (this.utility === UtilityLevel.EFFICIENT) {
              if (
                this.publicSafetyImpact === PublicSafetyImpactLevel.SIGNIFICANT
              ) {
                return ActionType.DECLINE;
              } else if (
                this.publicSafetyImpact === PublicSafetyImpactLevel.MINIMAL
              ) {
                return ActionType.DECLINE;
              }
            } else if (this.utility === UtilityLevel.LABORIOUS) {
              if (
                this.publicSafetyImpact === PublicSafetyImpactLevel.SIGNIFICANT
              ) {
                return ActionType.DECLINE;
              } else if (
                this.publicSafetyImpact === PublicSafetyImpactLevel.MINIMAL
              ) {
                return ActionType.DECLINE;
              }
            }
          } else if (
            this.supplierCardinality === SupplierCardinalityLevel.ONE
          ) {
            if (this.utility === UtilityLevel.SUPER_EFFECTIVE) {
              if (
                this.publicSafetyImpact === PublicSafetyImpactLevel.SIGNIFICANT
              ) {
                return ActionType.DECLINE;
              } else if (
                this.publicSafetyImpact === PublicSafetyImpactLevel.MINIMAL
              ) {
                return ActionType.DECLINE;
              }
            } else if (this.utility === UtilityLevel.EFFICIENT) {
              if (
                this.publicSafetyImpact === PublicSafetyImpactLevel.SIGNIFICANT
              ) {
                return ActionType.DECLINE;
              } else if (
                this.publicSafetyImpact === PublicSafetyImpactLevel.MINIMAL
              ) {
                return ActionType.DECLINE;
              }
            } else if (this.utility === UtilityLevel.LABORIOUS) {
              if (
                this.publicSafetyImpact === PublicSafetyImpactLevel.SIGNIFICANT
              ) {
                return ActionType.DECLINE;
              } else if (
                this.publicSafetyImpact === PublicSafetyImpactLevel.MINIMAL
              ) {
                return ActionType.DECLINE;
              }
            }
          }
        } else if (
          this.reportCredibility === ReportCredibilityLevel.NOT_CREDIBLE
        ) {
          if (this.supplierCardinality === SupplierCardinalityLevel.MULTIPLE) {
            if (this.utility === UtilityLevel.SUPER_EFFECTIVE) {
              if (
                this.publicSafetyImpact === PublicSafetyImpactLevel.SIGNIFICANT
              ) {
                return ActionType.DECLINE;
              } else if (
                this.publicSafetyImpact === PublicSafetyImpactLevel.MINIMAL
              ) {
                return ActionType.DECLINE;
              }
            } else if (this.utility === UtilityLevel.EFFICIENT) {
              if (
                this.publicSafetyImpact === PublicSafetyImpactLevel.SIGNIFICANT
              ) {
                return ActionType.DECLINE;
              } else if (
                this.publicSafetyImpact === PublicSafetyImpactLevel.MINIMAL
              ) {
                return ActionType.DECLINE;
              }
            } else if (this.utility === UtilityLevel.LABORIOUS) {
              if (
                this.publicSafetyImpact === PublicSafetyImpactLevel.SIGNIFICANT
              ) {
                return ActionType.DECLINE;
              } else if (
                this.publicSafetyImpact === PublicSafetyImpactLevel.MINIMAL
              ) {
                return ActionType.DECLINE;
              }
            }
          } else if (
            this.supplierCardinality === SupplierCardinalityLevel.ONE
          ) {
            if (this.utility === UtilityLevel.SUPER_EFFECTIVE) {
              if (
                this.publicSafetyImpact === PublicSafetyImpactLevel.SIGNIFICANT
              ) {
                return ActionType.DECLINE;
              } else if (
                this.publicSafetyImpact === PublicSafetyImpactLevel.MINIMAL
              ) {
                return ActionType.DECLINE;
              }
            } else if (this.utility === UtilityLevel.EFFICIENT) {
              if (
                this.publicSafetyImpact === PublicSafetyImpactLevel.SIGNIFICANT
              ) {
                return ActionType.DECLINE;
              } else if (
                this.publicSafetyImpact === PublicSafetyImpactLevel.MINIMAL
              ) {
                return ActionType.DECLINE;
              }
            } else if (this.utility === UtilityLevel.LABORIOUS) {
              if (
                this.publicSafetyImpact === PublicSafetyImpactLevel.SIGNIFICANT
              ) {
                return ActionType.DECLINE;
              } else if (
                this.publicSafetyImpact === PublicSafetyImpactLevel.MINIMAL
              ) {
                return ActionType.DECLINE;
              }
            }
          }
        }
      }
    } else if (this.reportPublic === ReportPublicStatus.NO) {
      if (this.supplierContacted === SupplierContactedStatus.YES) {
        if (this.reportCredibility === ReportCredibilityLevel.CREDIBLE) {
          if (this.supplierCardinality === SupplierCardinalityLevel.MULTIPLE) {
            if (this.utility === UtilityLevel.SUPER_EFFECTIVE) {
              if (
                this.publicSafetyImpact === PublicSafetyImpactLevel.SIGNIFICANT
              ) {
                return ActionType.COORDINATE;
              } else if (
                this.publicSafetyImpact === PublicSafetyImpactLevel.MINIMAL
              ) {
                return ActionType.TRACK;
              }
            } else if (this.utility === UtilityLevel.EFFICIENT) {
              if (
                this.publicSafetyImpact === PublicSafetyImpactLevel.SIGNIFICANT
              ) {
                return ActionType.TRACK;
              } else if (
                this.publicSafetyImpact === PublicSafetyImpactLevel.MINIMAL
              ) {
                return ActionType.TRACK;
              }
            } else if (this.utility === UtilityLevel.LABORIOUS) {
              if (
                this.publicSafetyImpact === PublicSafetyImpactLevel.SIGNIFICANT
              ) {
                return ActionType.COORDINATE;
              } else if (
                this.publicSafetyImpact === PublicSafetyImpactLevel.MINIMAL
              ) {
                return ActionType.COORDINATE;
              }
            }
          } else if (
            this.supplierCardinality === SupplierCardinalityLevel.ONE
          ) {
            if (this.utility === UtilityLevel.SUPER_EFFECTIVE) {
              if (
                this.publicSafetyImpact === PublicSafetyImpactLevel.SIGNIFICANT
              ) {
                return ActionType.TRACK;
              } else if (
                this.publicSafetyImpact === PublicSafetyImpactLevel.MINIMAL
              ) {
                return ActionType.TRACK;
              }
            } else if (this.utility === UtilityLevel.EFFICIENT) {
              if (
                this.publicSafetyImpact === PublicSafetyImpactLevel.SIGNIFICANT
              ) {
                return ActionType.TRACK;
              } else if (
                this.publicSafetyImpact === PublicSafetyImpactLevel.MINIMAL
              ) {
                return ActionType.DECLINE;
              }
            } else if (this.utility === UtilityLevel.LABORIOUS) {
              if (
                this.publicSafetyImpact === PublicSafetyImpactLevel.SIGNIFICANT
              ) {
                return ActionType.COORDINATE;
              } else if (
                this.publicSafetyImpact === PublicSafetyImpactLevel.MINIMAL
              ) {
                return ActionType.DECLINE;
              }
            }
          }
        } else if (
          this.reportCredibility === ReportCredibilityLevel.NOT_CREDIBLE
        ) {
          if (this.supplierCardinality === SupplierCardinalityLevel.MULTIPLE) {
            if (this.utility === UtilityLevel.SUPER_EFFECTIVE) {
              if (
                this.publicSafetyImpact === PublicSafetyImpactLevel.SIGNIFICANT
              ) {
                return ActionType.COORDINATE;
              } else if (
                this.publicSafetyImpact === PublicSafetyImpactLevel.MINIMAL
              ) {
                return ActionType.DECLINE;
              }
            } else if (this.utility === UtilityLevel.EFFICIENT) {
              if (
                this.publicSafetyImpact === PublicSafetyImpactLevel.SIGNIFICANT
              ) {
                return ActionType.DECLINE;
              } else if (
                this.publicSafetyImpact === PublicSafetyImpactLevel.MINIMAL
              ) {
                return ActionType.DECLINE;
              }
            } else if (this.utility === UtilityLevel.LABORIOUS) {
              if (
                this.publicSafetyImpact === PublicSafetyImpactLevel.SIGNIFICANT
              ) {
                return ActionType.DECLINE;
              } else if (
                this.publicSafetyImpact === PublicSafetyImpactLevel.MINIMAL
              ) {
                return ActionType.DECLINE;
              }
            }
          } else if (
            this.supplierCardinality === SupplierCardinalityLevel.ONE
          ) {
            if (this.utility === UtilityLevel.SUPER_EFFECTIVE) {
              if (
                this.publicSafetyImpact === PublicSafetyImpactLevel.SIGNIFICANT
              ) {
                return ActionType.DECLINE;
              } else if (
                this.publicSafetyImpact === PublicSafetyImpactLevel.MINIMAL
              ) {
                return ActionType.DECLINE;
              }
            } else if (this.utility === UtilityLevel.EFFICIENT) {
              if (
                this.publicSafetyImpact === PublicSafetyImpactLevel.SIGNIFICANT
              ) {
                return ActionType.DECLINE;
              } else if (
                this.publicSafetyImpact === PublicSafetyImpactLevel.MINIMAL
              ) {
                return ActionType.DECLINE;
              }
            } else if (this.utility === UtilityLevel.LABORIOUS) {
              if (
                this.publicSafetyImpact === PublicSafetyImpactLevel.SIGNIFICANT
              ) {
                return ActionType.DECLINE;
              } else if (
                this.publicSafetyImpact === PublicSafetyImpactLevel.MINIMAL
              ) {
                return ActionType.DECLINE;
              }
            }
          }
        }
      } else if (this.supplierContacted === SupplierContactedStatus.NO) {
        if (this.reportCredibility === ReportCredibilityLevel.CREDIBLE) {
          if (this.supplierCardinality === SupplierCardinalityLevel.MULTIPLE) {
            if (this.utility === UtilityLevel.SUPER_EFFECTIVE) {
              if (
                this.publicSafetyImpact === PublicSafetyImpactLevel.SIGNIFICANT
              ) {
                return ActionType.COORDINATE;
              } else if (
                this.publicSafetyImpact === PublicSafetyImpactLevel.MINIMAL
              ) {
                return ActionType.TRACK;
              }
            } else if (this.utility === UtilityLevel.EFFICIENT) {
              if (
                this.publicSafetyImpact === PublicSafetyImpactLevel.SIGNIFICANT
              ) {
                return ActionType.DECLINE;
              } else if (
                this.publicSafetyImpact === PublicSafetyImpactLevel.MINIMAL
              ) {
                return ActionType.DECLINE;
              }
            } else if (this.utility === UtilityLevel.LABORIOUS) {
              if (
                this.publicSafetyImpact === PublicSafetyImpactLevel.SIGNIFICANT
              ) {
                return ActionType.DECLINE;
              } else if (
                this.publicSafetyImpact === PublicSafetyImpactLevel.MINIMAL
              ) {
                return ActionType.DECLINE;
              }
            }
          } else if (
            this.supplierCardinality === SupplierCardinalityLevel.ONE
          ) {
            if (this.utility === UtilityLevel.SUPER_EFFECTIVE) {
              if (
                this.publicSafetyImpact === PublicSafetyImpactLevel.SIGNIFICANT
              ) {
                return ActionType.DECLINE;
              } else if (
                this.publicSafetyImpact === PublicSafetyImpactLevel.MINIMAL
              ) {
                return ActionType.DECLINE;
              }
            } else if (this.utility === UtilityLevel.EFFICIENT) {
              if (
                this.publicSafetyImpact === PublicSafetyImpactLevel.SIGNIFICANT
              ) {
                return ActionType.DECLINE;
              } else if (
                this.publicSafetyImpact === PublicSafetyImpactLevel.MINIMAL
              ) {
                return ActionType.DECLINE;
              }
            } else if (this.utility === UtilityLevel.LABORIOUS) {
              if (
                this.publicSafetyImpact === PublicSafetyImpactLevel.SIGNIFICANT
              ) {
                return ActionType.DECLINE;
              } else if (
                this.publicSafetyImpact === PublicSafetyImpactLevel.MINIMAL
              ) {
                return ActionType.DECLINE;
              }
            }
          }
        } else if (
          this.reportCredibility === ReportCredibilityLevel.NOT_CREDIBLE
        ) {
          if (this.supplierCardinality === SupplierCardinalityLevel.MULTIPLE) {
            if (this.utility === UtilityLevel.SUPER_EFFECTIVE) {
              if (
                this.publicSafetyImpact === PublicSafetyImpactLevel.SIGNIFICANT
              ) {
                return ActionType.DECLINE;
              } else if (
                this.publicSafetyImpact === PublicSafetyImpactLevel.MINIMAL
              ) {
                return ActionType.DECLINE;
              }
            } else if (this.utility === UtilityLevel.EFFICIENT) {
              if (
                this.publicSafetyImpact === PublicSafetyImpactLevel.SIGNIFICANT
              ) {
                return ActionType.DECLINE;
              } else if (
                this.publicSafetyImpact === PublicSafetyImpactLevel.MINIMAL
              ) {
                return ActionType.DECLINE;
              }
            } else if (this.utility === UtilityLevel.LABORIOUS) {
              if (
                this.publicSafetyImpact === PublicSafetyImpactLevel.SIGNIFICANT
              ) {
                return ActionType.DECLINE;
              } else if (
                this.publicSafetyImpact === PublicSafetyImpactLevel.MINIMAL
              ) {
                return ActionType.DECLINE;
              }
            }
          } else if (
            this.supplierCardinality === SupplierCardinalityLevel.ONE
          ) {
            if (this.utility === UtilityLevel.SUPER_EFFECTIVE) {
              if (
                this.publicSafetyImpact === PublicSafetyImpactLevel.SIGNIFICANT
              ) {
                return ActionType.DECLINE;
              } else if (
                this.publicSafetyImpact === PublicSafetyImpactLevel.MINIMAL
              ) {
                return ActionType.DECLINE;
              }
            } else if (this.utility === UtilityLevel.EFFICIENT) {
              if (
                this.publicSafetyImpact === PublicSafetyImpactLevel.SIGNIFICANT
              ) {
                return ActionType.DECLINE;
              } else if (
                this.publicSafetyImpact === PublicSafetyImpactLevel.MINIMAL
              ) {
                return ActionType.DECLINE;
              }
            } else if (this.utility === UtilityLevel.LABORIOUS) {
              if (
                this.publicSafetyImpact === PublicSafetyImpactLevel.SIGNIFICANT
              ) {
                return ActionType.DECLINE;
              } else if (
                this.publicSafetyImpact === PublicSafetyImpactLevel.MINIMAL
              ) {
                return ActionType.DECLINE;
              }
            }
          }
        }
      }
    }

    // Default action for unmapped paths
    return ActionType.DECLINE;
  }
}
