/**
 * Coordinator Publication Plugin
 *
 * CERT/CC Coordinator Publication Decision Model
 * Generated from YAML configuration.
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 * This file is auto-generated. To make changes:
 * 1. Edit the source YAML file: methodologies/coordinator_publication.yaml
 * 2. Run: yarn generate-plugins
 *
 * @generated true
 * @source methodologies/coordinator_publication.yaml
 * @generator scripts/generate-plugins.ts
 * @lastGenerated 2025-08-31T12:19:05.599Z
 */

export enum SupplierInvolvementLevel {
  fix_ready = "fix_ready",
  cooperative = "cooperative",
  uncooperative_unresponsive = "uncooperative_unresponsive",
}

export enum ExploitationStatus {
  none = "none",
  public_poc = "public_poc",
  active = "active",
}

export enum PublicValueAddedLevel {
  limited = "limited",
  ampliative = "ampliative",
  precedence = "precedence",
}

export enum ActionType {
  publish = "publish",
  dont_publish = "dont_publish",
}

export enum PriorityLevel {
  HIGH = "high",
  LOW = "low",
}

export const priorityMap = {
  [ActionType.publish]: PriorityLevel.HIGH,
  [ActionType.dont_publish]: PriorityLevel.LOW,
};

export class OutcomeCoordinatorPublication {
  priority: string;
  action: string;

  constructor(action: any) {
    this.priority = (priorityMap as any)[action];
    this.action = action;
  }
}

interface DecisionCoordinatorPublicationOptions {
  supplierInvolvement?: SupplierInvolvementLevel | string;
  exploitation?: ExploitationStatus | string;
  publicValueAdded?: PublicValueAddedLevel | string;
}

export class DecisionCoordinatorPublication {
  supplierInvolvement?: SupplierInvolvementLevel;
  exploitation?: ExploitationStatus;
  publicValueAdded?: PublicValueAddedLevel;
  outcome?: OutcomeCoordinatorPublication;

  constructor(options: DecisionCoordinatorPublicationOptions = {}) {
    if (typeof options.supplierInvolvement === "string") {
      this.supplierInvolvement =
        (Object.values(SupplierInvolvementLevel).find(
          (v) => v === options.supplierInvolvement,
        ) as SupplierInvolvementLevel) || undefined;
    } else {
      this.supplierInvolvement = options.supplierInvolvement;
    }
    if (typeof options.exploitation === "string") {
      this.exploitation =
        (Object.values(ExploitationStatus).find(
          (v) => v === options.exploitation,
        ) as ExploitationStatus) || undefined;
    } else {
      this.exploitation = options.exploitation;
    }
    if (typeof options.publicValueAdded === "string") {
      this.publicValueAdded =
        (Object.values(PublicValueAddedLevel).find(
          (v) => v === options.publicValueAdded,
        ) as PublicValueAddedLevel) || undefined;
    } else {
      this.publicValueAdded = options.publicValueAdded;
    }

    // Always try to evaluate if we have the minimum required parameters
    if (
      this.supplierInvolvement !== undefined &&
      this.exploitation !== undefined &&
      this.publicValueAdded !== undefined
    ) {
      this.outcome = this.evaluate();
    }
  }

  evaluate(): OutcomeCoordinatorPublication {
    const action = this.traverseTree();
    this.outcome = new OutcomeCoordinatorPublication(action);
    return this.outcome;
  }

  toVector(): string {
    if (!this.outcome) {
      this.evaluate();
    }

    const supplier_involvementVector =
      { fix_ready: "F", cooperative: "C", uncooperative_unresponsive: "U" }[
        this.supplierInvolvement?.toString?.()?.toUpperCase?.() ?? ""
      ] ||
      this.supplierInvolvement ||
      "";
    const exploitationVector =
      { none: "N", public_poc: "P", active: "A" }[
        this.exploitation?.toString?.()?.toUpperCase?.() ?? ""
      ] ||
      this.exploitation ||
      "";
    const public_value_addedVector =
      { limited: "L", ampliative: "A", precedence: "P" }[
        this.publicValueAdded?.toString?.()?.toUpperCase?.() ?? ""
      ] ||
      this.publicValueAdded ||
      "";
    const timestamp = new Date().toISOString();
    return `COORD_PUBv1/SI:${supplier_involvementVector}/E:${exploitationVector}/PV:${public_value_addedVector}/${timestamp}/`;
  }

  static fromVector(vectorString: string): DecisionCoordinatorPublication {
    const regex = /^COORD_PUBv1\/(.+)\/([0-9T:\-\.Z]+)\/?$/;
    const match = vectorString.match(regex);

    if (!match) {
      throw new Error(
        `Invalid vector string format for Coordinator Publication: ${vectorString}`,
      );
    }

    const paramsString = match[1];
    const params = new Map<string, string>();

    const paramPairs = paramsString.split("/");
    for (const pair of paramPairs) {
      const [key, value] = pair.split(":");
      if (key && value !== undefined) {
        params.set(key, value);
      }
    }

    const supplier_involvementMatch = params.get("SI");
    const exploitationMatch = params.get("E");
    const public_value_addedMatch = params.get("PV");

    return new DecisionCoordinatorPublication({
      supplierInvolvement:
        { F: "fix_ready", C: "cooperative", U: "uncooperative_unresponsive" }[
          supplier_involvementMatch || ""
        ] || supplier_involvementMatch,
      exploitation:
        { N: "none", P: "public_poc", A: "active" }[exploitationMatch || ""] ||
        exploitationMatch,
      publicValueAdded:
        { L: "limited", A: "ampliative", P: "precedence" }[
          public_value_addedMatch || ""
        ] || public_value_addedMatch,
    });
  }

  private traverseTree(): any {
    // Traverse the decision tree to determine the outcome
    if (this.supplierInvolvement === SupplierInvolvementLevel.fix_ready) {
      if (this.exploitation === ExploitationStatus.none) {
        if (this.publicValueAdded === PublicValueAddedLevel.limited) {
          return ActionType.dont_publish;
        } else if (this.publicValueAdded === PublicValueAddedLevel.ampliative) {
          return ActionType.publish;
        } else if (this.publicValueAdded === PublicValueAddedLevel.precedence) {
          return ActionType.publish;
        }
      } else if (this.exploitation === ExploitationStatus.public_poc) {
        if (this.publicValueAdded === PublicValueAddedLevel.limited) {
          return ActionType.dont_publish;
        } else if (this.publicValueAdded === PublicValueAddedLevel.ampliative) {
          return ActionType.publish;
        } else if (this.publicValueAdded === PublicValueAddedLevel.precedence) {
          return ActionType.publish;
        }
      } else if (this.exploitation === ExploitationStatus.active) {
        if (this.publicValueAdded === PublicValueAddedLevel.limited) {
          return ActionType.publish;
        } else if (this.publicValueAdded === PublicValueAddedLevel.ampliative) {
          return ActionType.publish;
        } else if (this.publicValueAdded === PublicValueAddedLevel.precedence) {
          return ActionType.publish;
        }
      }
    } else if (
      this.supplierInvolvement === SupplierInvolvementLevel.cooperative
    ) {
      if (this.exploitation === ExploitationStatus.none) {
        if (this.publicValueAdded === PublicValueAddedLevel.limited) {
          return ActionType.dont_publish;
        } else if (this.publicValueAdded === PublicValueAddedLevel.ampliative) {
          return ActionType.dont_publish;
        } else if (this.publicValueAdded === PublicValueAddedLevel.precedence) {
          return ActionType.publish;
        }
      } else if (this.exploitation === ExploitationStatus.public_poc) {
        if (this.publicValueAdded === PublicValueAddedLevel.limited) {
          return ActionType.dont_publish;
        } else if (this.publicValueAdded === PublicValueAddedLevel.ampliative) {
          return ActionType.publish;
        } else if (this.publicValueAdded === PublicValueAddedLevel.precedence) {
          return ActionType.publish;
        }
      } else if (this.exploitation === ExploitationStatus.active) {
        if (this.publicValueAdded === PublicValueAddedLevel.limited) {
          return ActionType.publish;
        } else if (this.publicValueAdded === PublicValueAddedLevel.ampliative) {
          return ActionType.publish;
        } else if (this.publicValueAdded === PublicValueAddedLevel.precedence) {
          return ActionType.publish;
        }
      }
    } else if (
      this.supplierInvolvement ===
      SupplierInvolvementLevel.uncooperative_unresponsive
    ) {
      if (this.exploitation === ExploitationStatus.none) {
        if (this.publicValueAdded === PublicValueAddedLevel.limited) {
          return ActionType.dont_publish;
        } else if (this.publicValueAdded === PublicValueAddedLevel.ampliative) {
          return ActionType.dont_publish;
        } else if (this.publicValueAdded === PublicValueAddedLevel.precedence) {
          return ActionType.publish;
        }
      } else if (this.exploitation === ExploitationStatus.public_poc) {
        if (this.publicValueAdded === PublicValueAddedLevel.limited) {
          return ActionType.publish;
        } else if (this.publicValueAdded === PublicValueAddedLevel.ampliative) {
          return ActionType.publish;
        } else if (this.publicValueAdded === PublicValueAddedLevel.precedence) {
          return ActionType.publish;
        }
      } else if (this.exploitation === ExploitationStatus.active) {
        if (this.publicValueAdded === PublicValueAddedLevel.limited) {
          return ActionType.publish;
        } else if (this.publicValueAdded === PublicValueAddedLevel.ampliative) {
          return ActionType.publish;
        } else if (this.publicValueAdded === PublicValueAddedLevel.precedence) {
          return ActionType.publish;
        }
      }
    }

    // Default action for unmapped paths
    return ActionType.dont_publish;
  }
}
