/**
 * Engineer Triage Plugin
 *
 * Developer-focused vulnerability triage methodology for determining appropriate response actions based on reachability, remediation options, mitigation capabilities, and priority
 * Generated from YAML configuration.
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 * This file is auto-generated. To make changes:
 * 1. Edit the source YAML file: methodologies/engineer_triage.yaml
 * 2. Run: yarn generate-plugins
 *
 * @generated true
 * @source methodologies/engineer_triage.yaml
 * @generator scripts/generate-plugins.ts
 * @lastGenerated 2025-09-01T14:11:10.183Z
 */

export enum Reachability {
  VERIFIED_REACHABLE = "verified_reachable",
  VERIFIED_UNREACHABLE = "verified_unreachable",
  UNKNOWN = "unknown",
}

export enum RemediationOption {
  PATCHABLE_VERSION_LOCKED = "patchable_version_locked",
  PATCHABLE_DEPLOYMENT = "patchable_deployment",
  PATCHABLE_MANUAL = "patchable_manual",
  PATCH_UNAVAILABLE = "patch_unavailable",
  NO_PATCH = "no_patch",
}

export enum MitigationOption {
  INFRASTRUCTURE = "infrastructure",
  CODE_CHANGE = "code_change",
  UPSTREAM_PR = "upstream_pr",
  ALTERNATIVE = "alternative",
  AUTOMATION = "automation",
}

export enum ReportedPriority {
  CRITICAL = "critical",
  HIGH = "high",
  MEDIUM = "medium",
  LOW = "low",
}

export enum ActionType {
  NIGHTLY_AUTO_PATCH = "NIGHTLY_AUTO_PATCH",
  DROP_TOOLS = "DROP_TOOLS",
  SPIKE_EFFORT = "SPIKE_EFFORT",
  BACKLOG = "BACKLOG",
}

export enum PriorityLevel {
  LOW = "low",
  IMMEDIATE = "immediate",
  HIGH = "high",
  MEDIUM = "medium",
}

export const priorityMap = {
  [ActionType.NIGHTLY_AUTO_PATCH]: PriorityLevel.LOW,
  [ActionType.DROP_TOOLS]: PriorityLevel.IMMEDIATE,
  [ActionType.SPIKE_EFFORT]: PriorityLevel.HIGH,
  [ActionType.BACKLOG]: PriorityLevel.MEDIUM,
};

export class OutcomeEngineerTriage {
  priority: string;
  action: string;

  constructor(action: any) {
    this.priority = (priorityMap as any)[action];
    this.action = action;
  }
}

interface DecisionEngineerTriageOptions {
  reachability?: Reachability | string;
  remediationOption?: RemediationOption | string;
  mitigationOption?: MitigationOption | string;
  reportedPriority?: ReportedPriority | string;
}

export class DecisionEngineerTriage {
  reachability?: Reachability;
  remediationOption?: RemediationOption;
  mitigationOption?: MitigationOption;
  reportedPriority?: ReportedPriority;
  outcome?: OutcomeEngineerTriage;

  constructor(options: DecisionEngineerTriageOptions = {}) {
    if (typeof options.reachability === "string") {
      this.reachability =
        (Object.values(Reachability).find(
          (v) => v === options.reachability,
        ) as Reachability) || undefined;
    } else {
      this.reachability = options.reachability;
    }
    if (typeof options.remediationOption === "string") {
      this.remediationOption =
        (Object.values(RemediationOption).find(
          (v) => v === options.remediationOption,
        ) as RemediationOption) || undefined;
    } else {
      this.remediationOption = options.remediationOption;
    }
    if (typeof options.mitigationOption === "string") {
      this.mitigationOption =
        (Object.values(MitigationOption).find(
          (v) => v === options.mitigationOption,
        ) as MitigationOption) || undefined;
    } else {
      this.mitigationOption = options.mitigationOption;
    }
    if (typeof options.reportedPriority === "string") {
      this.reportedPriority =
        (Object.values(ReportedPriority).find(
          (v) => v === options.reportedPriority,
        ) as ReportedPriority) || undefined;
    } else {
      this.reportedPriority = options.reportedPriority;
    }

    // Always try to evaluate if we have the minimum required parameters
    if (
      this.reachability !== undefined &&
      this.remediationOption !== undefined &&
      this.mitigationOption !== undefined &&
      this.reportedPriority !== undefined
    ) {
      this.outcome = this.evaluate();
    }
  }

  evaluate(): OutcomeEngineerTriage {
    const action = this.traverseTree();
    this.outcome = new OutcomeEngineerTriage(action);
    return this.outcome;
  }

  toVector(): string {
    if (!this.outcome) {
      this.evaluate();
    }

    const reachabilityVector =
      { VERIFIED_REACHABLE: "VR", VERIFIED_UNREACHABLE: "VU", UNKNOWN: "U" }[
        this.reachability?.toString?.()?.toUpperCase?.() ?? ""
      ] ||
      this.reachability ||
      "";
    const remediation_optionVector =
      {
        PATCHABLE_VERSION_LOCKED: "PVL",
        PATCHABLE_DEPLOYMENT: "PD",
        PATCHABLE_MANUAL: "PM",
        PATCH_UNAVAILABLE: "PU",
        NO_PATCH: "NP",
      }[this.remediationOption?.toString?.()?.toUpperCase?.() ?? ""] ||
      this.remediationOption ||
      "";
    const mitigation_optionVector =
      {
        INFRASTRUCTURE: "I",
        CODE_CHANGE: "CC",
        UPSTREAM_PR: "UP",
        ALTERNATIVE: "A",
        AUTOMATION: "AU",
      }[this.mitigationOption?.toString?.()?.toUpperCase?.() ?? ""] ||
      this.mitigationOption ||
      "";
    const reported_priorityVector =
      { CRITICAL: "C", HIGH: "H", MEDIUM: "M", LOW: "L" }[
        this.reportedPriority?.toString?.()?.toUpperCase?.() ?? ""
      ] ||
      this.reportedPriority ||
      "";
    const timestamp = new Date().toISOString();
    return `DEVELv1/R:${reachabilityVector}/RO:${remediation_optionVector}/MO:${mitigation_optionVector}/RP:${reported_priorityVector}/${timestamp}/`;
  }

  static fromVector(vectorString: string): DecisionEngineerTriage {
    const regex = /^DEVELv1\/(.+)\/([0-9T:\-\.Z]+)\/?$/;
    const match = vectorString.match(regex);

    if (!match) {
      throw new Error(
        `Invalid vector string format for Engineer Triage: ${vectorString}`,
      );
    }

    const paramsString = match[1];
    const params = new Map<string, string>();

    const paramPairs = paramsString.split("/");
    for (const pair of paramPairs) {
      const [key, value] = pair.split(":");
      if (key && value !== undefined) {
        params.set(key, value);
      }
    }

    const reachabilityMatch = params.get("R");
    const remediation_optionMatch = params.get("RO");
    const mitigation_optionMatch = params.get("MO");
    const reported_priorityMatch = params.get("RP");

    return new DecisionEngineerTriage({
      reachability:
        { VR: "VERIFIED_REACHABLE", VU: "VERIFIED_UNREACHABLE", U: "UNKNOWN" }[
          reachabilityMatch || ""
        ] || reachabilityMatch,
      remediationOption:
        {
          PVL: "PATCHABLE_VERSION_LOCKED",
          PD: "PATCHABLE_DEPLOYMENT",
          PM: "PATCHABLE_MANUAL",
          PU: "PATCH_UNAVAILABLE",
          NP: "NO_PATCH",
        }[remediation_optionMatch || ""] || remediation_optionMatch,
      mitigationOption:
        {
          I: "INFRASTRUCTURE",
          CC: "CODE_CHANGE",
          UP: "UPSTREAM_PR",
          A: "ALTERNATIVE",
          AU: "AUTOMATION",
        }[mitigation_optionMatch || ""] || mitigation_optionMatch,
      reportedPriority:
        { C: "CRITICAL", H: "HIGH", M: "MEDIUM", L: "LOW" }[
          reported_priorityMatch || ""
        ] || reported_priorityMatch,
    });
  }

  private traverseTree(): any {
    // Traverse the decision tree to determine the outcome
    if (this.reachability === Reachability.VERIFIED_REACHABLE) {
      if (this.remediationOption === RemediationOption.PATCHABLE_DEPLOYMENT) {
        if (this.mitigationOption === MitigationOption.AUTOMATION) {
          if (this.reportedPriority === ReportedPriority.CRITICAL) {
            return ActionType.SPIKE_EFFORT;
          } else if (this.reportedPriority === ReportedPriority.HIGH) {
            return ActionType.NIGHTLY_AUTO_PATCH;
          } else if (this.reportedPriority === ReportedPriority.MEDIUM) {
            return ActionType.NIGHTLY_AUTO_PATCH;
          } else if (this.reportedPriority === ReportedPriority.LOW) {
            return ActionType.NIGHTLY_AUTO_PATCH;
          }
        }
      } else if (
        this.remediationOption === RemediationOption.PATCHABLE_VERSION_LOCKED
      ) {
        if (this.mitigationOption === MitigationOption.CODE_CHANGE) {
          if (this.reportedPriority === ReportedPriority.CRITICAL) {
            return ActionType.DROP_TOOLS;
          } else if (this.reportedPriority === ReportedPriority.HIGH) {
            return ActionType.DROP_TOOLS;
          } else if (this.reportedPriority === ReportedPriority.MEDIUM) {
            return ActionType.SPIKE_EFFORT;
          } else if (this.reportedPriority === ReportedPriority.LOW) {
            return ActionType.SPIKE_EFFORT;
          }
        }
      } else if (
        this.remediationOption === RemediationOption.PATCHABLE_MANUAL
      ) {
        if (this.mitigationOption === MitigationOption.CODE_CHANGE) {
          if (this.reportedPriority === ReportedPriority.CRITICAL) {
            return ActionType.DROP_TOOLS;
          } else if (this.reportedPriority === ReportedPriority.HIGH) {
            return ActionType.DROP_TOOLS;
          } else if (this.reportedPriority === ReportedPriority.MEDIUM) {
            return ActionType.NIGHTLY_AUTO_PATCH;
          } else if (this.reportedPriority === ReportedPriority.LOW) {
            return ActionType.NIGHTLY_AUTO_PATCH;
          }
        }
      } else if (
        this.remediationOption === RemediationOption.PATCH_UNAVAILABLE
      ) {
        if (this.mitigationOption === MitigationOption.INFRASTRUCTURE) {
          if (this.reportedPriority === ReportedPriority.CRITICAL) {
            return ActionType.DROP_TOOLS;
          } else if (this.reportedPriority === ReportedPriority.HIGH) {
            return ActionType.DROP_TOOLS;
          } else if (this.reportedPriority === ReportedPriority.MEDIUM) {
            return ActionType.SPIKE_EFFORT;
          } else if (this.reportedPriority === ReportedPriority.LOW) {
            return ActionType.BACKLOG;
          }
        } else if (this.mitigationOption === MitigationOption.CODE_CHANGE) {
          if (this.reportedPriority === ReportedPriority.CRITICAL) {
            return ActionType.DROP_TOOLS;
          } else if (this.reportedPriority === ReportedPriority.HIGH) {
            return ActionType.DROP_TOOLS;
          } else if (this.reportedPriority === ReportedPriority.MEDIUM) {
            return ActionType.SPIKE_EFFORT;
          } else if (this.reportedPriority === ReportedPriority.LOW) {
            return ActionType.BACKLOG;
          }
        } else if (this.mitigationOption === MitigationOption.UPSTREAM_PR) {
          if (this.reportedPriority === ReportedPriority.CRITICAL) {
            return ActionType.DROP_TOOLS;
          } else if (this.reportedPriority === ReportedPriority.HIGH) {
            return ActionType.SPIKE_EFFORT;
          } else if (this.reportedPriority === ReportedPriority.MEDIUM) {
            return ActionType.SPIKE_EFFORT;
          } else if (this.reportedPriority === ReportedPriority.LOW) {
            return ActionType.SPIKE_EFFORT;
          }
        } else if (this.mitigationOption === MitigationOption.ALTERNATIVE) {
          if (this.reportedPriority === ReportedPriority.CRITICAL) {
            return ActionType.DROP_TOOLS;
          } else if (this.reportedPriority === ReportedPriority.HIGH) {
            return ActionType.DROP_TOOLS;
          } else if (this.reportedPriority === ReportedPriority.MEDIUM) {
            return ActionType.SPIKE_EFFORT;
          } else if (this.reportedPriority === ReportedPriority.LOW) {
            return ActionType.SPIKE_EFFORT;
          }
        }
      } else if (this.remediationOption === RemediationOption.NO_PATCH) {
        if (this.mitigationOption === MitigationOption.INFRASTRUCTURE) {
          if (this.reportedPriority === ReportedPriority.CRITICAL) {
            return ActionType.DROP_TOOLS;
          } else if (this.reportedPriority === ReportedPriority.HIGH) {
            return ActionType.DROP_TOOLS;
          } else if (this.reportedPriority === ReportedPriority.MEDIUM) {
            return ActionType.SPIKE_EFFORT;
          } else if (this.reportedPriority === ReportedPriority.LOW) {
            return ActionType.BACKLOG;
          }
        } else if (this.mitigationOption === MitigationOption.CODE_CHANGE) {
          if (this.reportedPriority === ReportedPriority.CRITICAL) {
            return ActionType.DROP_TOOLS;
          } else if (this.reportedPriority === ReportedPriority.HIGH) {
            return ActionType.DROP_TOOLS;
          } else if (this.reportedPriority === ReportedPriority.MEDIUM) {
            return ActionType.SPIKE_EFFORT;
          } else if (this.reportedPriority === ReportedPriority.LOW) {
            return ActionType.SPIKE_EFFORT;
          }
        } else if (this.mitigationOption === MitigationOption.UPSTREAM_PR) {
          if (this.reportedPriority === ReportedPriority.CRITICAL) {
            return ActionType.DROP_TOOLS;
          } else if (this.reportedPriority === ReportedPriority.HIGH) {
            return ActionType.SPIKE_EFFORT;
          } else if (this.reportedPriority === ReportedPriority.MEDIUM) {
            return ActionType.SPIKE_EFFORT;
          } else if (this.reportedPriority === ReportedPriority.LOW) {
            return ActionType.SPIKE_EFFORT;
          }
        } else if (this.mitigationOption === MitigationOption.ALTERNATIVE) {
          if (this.reportedPriority === ReportedPriority.CRITICAL) {
            return ActionType.DROP_TOOLS;
          } else if (this.reportedPriority === ReportedPriority.HIGH) {
            return ActionType.DROP_TOOLS;
          } else if (this.reportedPriority === ReportedPriority.MEDIUM) {
            return ActionType.SPIKE_EFFORT;
          } else if (this.reportedPriority === ReportedPriority.LOW) {
            return ActionType.BACKLOG;
          }
        }
      }
    } else if (this.reachability === Reachability.VERIFIED_UNREACHABLE) {
      if (this.remediationOption === RemediationOption.PATCHABLE_DEPLOYMENT) {
        if (this.mitigationOption === MitigationOption.AUTOMATION) {
          if (this.reportedPriority === ReportedPriority.CRITICAL) {
            return ActionType.NIGHTLY_AUTO_PATCH;
          } else if (this.reportedPriority === ReportedPriority.HIGH) {
            return ActionType.NIGHTLY_AUTO_PATCH;
          } else if (this.reportedPriority === ReportedPriority.MEDIUM) {
            return ActionType.NIGHTLY_AUTO_PATCH;
          } else if (this.reportedPriority === ReportedPriority.LOW) {
            return ActionType.NIGHTLY_AUTO_PATCH;
          }
        }
      } else if (
        this.remediationOption === RemediationOption.PATCHABLE_VERSION_LOCKED
      ) {
        if (this.mitigationOption === MitigationOption.CODE_CHANGE) {
          if (this.reportedPriority === ReportedPriority.CRITICAL) {
            return ActionType.SPIKE_EFFORT;
          } else if (this.reportedPriority === ReportedPriority.HIGH) {
            return ActionType.SPIKE_EFFORT;
          } else if (this.reportedPriority === ReportedPriority.MEDIUM) {
            return ActionType.BACKLOG;
          } else if (this.reportedPriority === ReportedPriority.LOW) {
            return ActionType.BACKLOG;
          }
        }
      } else if (
        this.remediationOption === RemediationOption.PATCHABLE_MANUAL
      ) {
        if (this.mitigationOption === MitigationOption.CODE_CHANGE) {
          if (this.reportedPriority === ReportedPriority.CRITICAL) {
            return ActionType.SPIKE_EFFORT;
          } else if (this.reportedPriority === ReportedPriority.HIGH) {
            return ActionType.BACKLOG;
          } else if (this.reportedPriority === ReportedPriority.MEDIUM) {
            return ActionType.BACKLOG;
          } else if (this.reportedPriority === ReportedPriority.LOW) {
            return ActionType.BACKLOG;
          }
        }
      } else if (
        this.remediationOption === RemediationOption.PATCH_UNAVAILABLE
      ) {
        if (this.mitigationOption === MitigationOption.INFRASTRUCTURE) {
          if (this.reportedPriority === ReportedPriority.CRITICAL) {
            return ActionType.SPIKE_EFFORT;
          } else if (this.reportedPriority === ReportedPriority.HIGH) {
            return ActionType.BACKLOG;
          } else if (this.reportedPriority === ReportedPriority.MEDIUM) {
            return ActionType.BACKLOG;
          } else if (this.reportedPriority === ReportedPriority.LOW) {
            return ActionType.BACKLOG;
          }
        } else if (this.mitigationOption === MitigationOption.CODE_CHANGE) {
          if (this.reportedPriority === ReportedPriority.CRITICAL) {
            return ActionType.SPIKE_EFFORT;
          } else if (this.reportedPriority === ReportedPriority.HIGH) {
            return ActionType.BACKLOG;
          } else if (this.reportedPriority === ReportedPriority.MEDIUM) {
            return ActionType.BACKLOG;
          } else if (this.reportedPriority === ReportedPriority.LOW) {
            return ActionType.BACKLOG;
          }
        } else if (this.mitigationOption === MitigationOption.UPSTREAM_PR) {
          if (this.reportedPriority === ReportedPriority.CRITICAL) {
            return ActionType.SPIKE_EFFORT;
          } else if (this.reportedPriority === ReportedPriority.HIGH) {
            return ActionType.SPIKE_EFFORT;
          } else if (this.reportedPriority === ReportedPriority.MEDIUM) {
            return ActionType.SPIKE_EFFORT;
          } else if (this.reportedPriority === ReportedPriority.LOW) {
            return ActionType.BACKLOG;
          }
        } else if (this.mitigationOption === MitigationOption.ALTERNATIVE) {
          if (this.reportedPriority === ReportedPriority.CRITICAL) {
            return ActionType.SPIKE_EFFORT;
          } else if (this.reportedPriority === ReportedPriority.HIGH) {
            return ActionType.SPIKE_EFFORT;
          } else if (this.reportedPriority === ReportedPriority.MEDIUM) {
            return ActionType.SPIKE_EFFORT;
          } else if (this.reportedPriority === ReportedPriority.LOW) {
            return ActionType.BACKLOG;
          }
        }
      } else if (this.remediationOption === RemediationOption.NO_PATCH) {
        if (this.mitigationOption === MitigationOption.INFRASTRUCTURE) {
          if (this.reportedPriority === ReportedPriority.CRITICAL) {
            return ActionType.SPIKE_EFFORT;
          } else if (this.reportedPriority === ReportedPriority.HIGH) {
            return ActionType.SPIKE_EFFORT;
          } else if (this.reportedPriority === ReportedPriority.MEDIUM) {
            return ActionType.SPIKE_EFFORT;
          } else if (this.reportedPriority === ReportedPriority.LOW) {
            return ActionType.BACKLOG;
          }
        } else if (this.mitigationOption === MitigationOption.CODE_CHANGE) {
          if (this.reportedPriority === ReportedPriority.CRITICAL) {
            return ActionType.SPIKE_EFFORT;
          } else if (this.reportedPriority === ReportedPriority.HIGH) {
            return ActionType.BACKLOG;
          } else if (this.reportedPriority === ReportedPriority.MEDIUM) {
            return ActionType.BACKLOG;
          } else if (this.reportedPriority === ReportedPriority.LOW) {
            return ActionType.BACKLOG;
          }
        } else if (this.mitigationOption === MitigationOption.UPSTREAM_PR) {
          if (this.reportedPriority === ReportedPriority.CRITICAL) {
            return ActionType.SPIKE_EFFORT;
          } else if (this.reportedPriority === ReportedPriority.HIGH) {
            return ActionType.SPIKE_EFFORT;
          } else if (this.reportedPriority === ReportedPriority.MEDIUM) {
            return ActionType.SPIKE_EFFORT;
          } else if (this.reportedPriority === ReportedPriority.LOW) {
            return ActionType.BACKLOG;
          }
        } else if (this.mitigationOption === MitigationOption.ALTERNATIVE) {
          if (this.reportedPriority === ReportedPriority.CRITICAL) {
            return ActionType.SPIKE_EFFORT;
          } else if (this.reportedPriority === ReportedPriority.HIGH) {
            return ActionType.SPIKE_EFFORT;
          } else if (this.reportedPriority === ReportedPriority.MEDIUM) {
            return ActionType.BACKLOG;
          } else if (this.reportedPriority === ReportedPriority.LOW) {
            return ActionType.BACKLOG;
          }
        }
      }
    } else if (this.reachability === Reachability.UNKNOWN) {
      if (this.remediationOption === RemediationOption.PATCHABLE_DEPLOYMENT) {
        if (this.mitigationOption === MitigationOption.AUTOMATION) {
          if (this.reportedPriority === ReportedPriority.CRITICAL) {
            return ActionType.DROP_TOOLS;
          } else if (this.reportedPriority === ReportedPriority.HIGH) {
            return ActionType.NIGHTLY_AUTO_PATCH;
          } else if (this.reportedPriority === ReportedPriority.MEDIUM) {
            return ActionType.NIGHTLY_AUTO_PATCH;
          } else if (this.reportedPriority === ReportedPriority.LOW) {
            return ActionType.NIGHTLY_AUTO_PATCH;
          }
        }
      } else if (
        this.remediationOption === RemediationOption.PATCHABLE_VERSION_LOCKED
      ) {
        if (this.mitigationOption === MitigationOption.CODE_CHANGE) {
          if (this.reportedPriority === ReportedPriority.CRITICAL) {
            return ActionType.DROP_TOOLS;
          } else if (this.reportedPriority === ReportedPriority.HIGH) {
            return ActionType.DROP_TOOLS;
          } else if (this.reportedPriority === ReportedPriority.MEDIUM) {
            return ActionType.SPIKE_EFFORT;
          } else if (this.reportedPriority === ReportedPriority.LOW) {
            return ActionType.SPIKE_EFFORT;
          }
        }
      } else if (
        this.remediationOption === RemediationOption.PATCHABLE_MANUAL
      ) {
        if (this.mitigationOption === MitigationOption.CODE_CHANGE) {
          if (this.reportedPriority === ReportedPriority.CRITICAL) {
            return ActionType.DROP_TOOLS;
          } else if (this.reportedPriority === ReportedPriority.HIGH) {
            return ActionType.DROP_TOOLS;
          } else if (this.reportedPriority === ReportedPriority.MEDIUM) {
            return ActionType.SPIKE_EFFORT;
          } else if (this.reportedPriority === ReportedPriority.LOW) {
            return ActionType.SPIKE_EFFORT;
          }
        }
      } else if (
        this.remediationOption === RemediationOption.PATCH_UNAVAILABLE
      ) {
        if (this.mitigationOption === MitigationOption.INFRASTRUCTURE) {
          if (this.reportedPriority === ReportedPriority.CRITICAL) {
            return ActionType.DROP_TOOLS;
          } else if (this.reportedPriority === ReportedPriority.HIGH) {
            return ActionType.DROP_TOOLS;
          } else if (this.reportedPriority === ReportedPriority.MEDIUM) {
            return ActionType.SPIKE_EFFORT;
          } else if (this.reportedPriority === ReportedPriority.LOW) {
            return ActionType.SPIKE_EFFORT;
          }
        } else if (this.mitigationOption === MitigationOption.CODE_CHANGE) {
          if (this.reportedPriority === ReportedPriority.CRITICAL) {
            return ActionType.DROP_TOOLS;
          } else if (this.reportedPriority === ReportedPriority.HIGH) {
            return ActionType.DROP_TOOLS;
          } else if (this.reportedPriority === ReportedPriority.MEDIUM) {
            return ActionType.SPIKE_EFFORT;
          } else if (this.reportedPriority === ReportedPriority.LOW) {
            return ActionType.BACKLOG;
          }
        } else if (this.mitigationOption === MitigationOption.UPSTREAM_PR) {
          if (this.reportedPriority === ReportedPriority.CRITICAL) {
            return ActionType.DROP_TOOLS;
          } else if (this.reportedPriority === ReportedPriority.HIGH) {
            return ActionType.DROP_TOOLS;
          } else if (this.reportedPriority === ReportedPriority.MEDIUM) {
            return ActionType.SPIKE_EFFORT;
          } else if (this.reportedPriority === ReportedPriority.LOW) {
            return ActionType.SPIKE_EFFORT;
          }
        } else if (this.mitigationOption === MitigationOption.ALTERNATIVE) {
          if (this.reportedPriority === ReportedPriority.CRITICAL) {
            return ActionType.DROP_TOOLS;
          } else if (this.reportedPriority === ReportedPriority.HIGH) {
            return ActionType.DROP_TOOLS;
          } else if (this.reportedPriority === ReportedPriority.MEDIUM) {
            return ActionType.SPIKE_EFFORT;
          } else if (this.reportedPriority === ReportedPriority.LOW) {
            return ActionType.SPIKE_EFFORT;
          }
        }
      } else if (this.remediationOption === RemediationOption.NO_PATCH) {
        if (this.mitigationOption === MitigationOption.INFRASTRUCTURE) {
          if (this.reportedPriority === ReportedPriority.CRITICAL) {
            return ActionType.DROP_TOOLS;
          } else if (this.reportedPriority === ReportedPriority.HIGH) {
            return ActionType.DROP_TOOLS;
          } else if (this.reportedPriority === ReportedPriority.MEDIUM) {
            return ActionType.SPIKE_EFFORT;
          } else if (this.reportedPriority === ReportedPriority.LOW) {
            return ActionType.SPIKE_EFFORT;
          }
        } else if (this.mitigationOption === MitigationOption.CODE_CHANGE) {
          if (this.reportedPriority === ReportedPriority.CRITICAL) {
            return ActionType.DROP_TOOLS;
          } else if (this.reportedPriority === ReportedPriority.HIGH) {
            return ActionType.DROP_TOOLS;
          } else if (this.reportedPriority === ReportedPriority.MEDIUM) {
            return ActionType.DROP_TOOLS;
          } else if (this.reportedPriority === ReportedPriority.LOW) {
            return ActionType.SPIKE_EFFORT;
          }
        } else if (this.mitigationOption === MitigationOption.UPSTREAM_PR) {
          if (this.reportedPriority === ReportedPriority.CRITICAL) {
            return ActionType.DROP_TOOLS;
          } else if (this.reportedPriority === ReportedPriority.HIGH) {
            return ActionType.DROP_TOOLS;
          } else if (this.reportedPriority === ReportedPriority.MEDIUM) {
            return ActionType.DROP_TOOLS;
          } else if (this.reportedPriority === ReportedPriority.LOW) {
            return ActionType.SPIKE_EFFORT;
          }
        } else if (this.mitigationOption === MitigationOption.ALTERNATIVE) {
          if (this.reportedPriority === ReportedPriority.CRITICAL) {
            return ActionType.DROP_TOOLS;
          } else if (this.reportedPriority === ReportedPriority.HIGH) {
            return ActionType.DROP_TOOLS;
          } else if (this.reportedPriority === ReportedPriority.MEDIUM) {
            return ActionType.SPIKE_EFFORT;
          } else if (this.reportedPriority === ReportedPriority.LOW) {
            return ActionType.SPIKE_EFFORT;
          }
        }
      }
    }

    // Default action for unmapped paths
    return ActionType.NIGHTLY_AUTO_PATCH;
  }
}
