/**
 * Supplier Plugin
 *
 * CERT/CC Supplier Decision Model
 * Generated from YAML configuration.
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 * This file is auto-generated. To make changes:
 * 1. Edit the source YAML file: methodologies/supplier.yaml
 * 2. Run: yarn generate-plugins
 *
 * @generated true
 * @source methodologies/supplier.yaml
 * @generator scripts/generate-plugins.ts
 * @lastGenerated 2025-08-31T12:19:11.913Z
 */

export enum ExploitationStatus {
  none = "none",
  public_poc = "public_poc",
  active = "active",
}

export enum UtilityLevel {
  laborious = "laborious",
  efficient = "efficient",
  super_effective = "super_effective",
}

export enum TechnicalImpactLevel {
  partial = "partial",
  total = "total",
}

export enum PublicSafetyImpactLevel {
  minimal = "minimal",
  significant = "significant",
}

export enum ActionType {
  defer = "defer",
  scheduled = "scheduled",
  out_of_cycle = "out_of_cycle",
  immediate = "immediate",
}

export enum PriorityLevel {
  LOW = "low",
  MEDIUM = "medium",
  HIGH = "high",
  IMMEDIATE = "immediate",
}

export const priorityMap = {
  [ActionType.defer]: PriorityLevel.LOW,
  [ActionType.scheduled]: PriorityLevel.MEDIUM,
  [ActionType.out_of_cycle]: PriorityLevel.HIGH,
  [ActionType.immediate]: PriorityLevel.IMMEDIATE,
};

export class OutcomeSupplier {
  priority: string;
  action: string;

  constructor(action: any) {
    this.priority = (priorityMap as any)[action];
    this.action = action;
  }
}

interface DecisionSupplierOptions {
  exploitation?: ExploitationStatus | string;
  utility?: UtilityLevel | string;
  technicalImpact?: TechnicalImpactLevel | string;
  publicSafetyImpact?: PublicSafetyImpactLevel | string;
}

export class DecisionSupplier {
  exploitation?: ExploitationStatus;
  utility?: UtilityLevel;
  technicalImpact?: TechnicalImpactLevel;
  publicSafetyImpact?: PublicSafetyImpactLevel;
  outcome?: OutcomeSupplier;

  constructor(options: DecisionSupplierOptions = {}) {
    if (typeof options.exploitation === "string") {
      this.exploitation =
        (Object.values(ExploitationStatus).find(
          (v) => v === options.exploitation,
        ) as ExploitationStatus) || undefined;
    } else {
      this.exploitation = options.exploitation;
    }
    if (typeof options.utility === "string") {
      this.utility =
        (Object.values(UtilityLevel).find(
          (v) => v === options.utility,
        ) as UtilityLevel) || undefined;
    } else {
      this.utility = options.utility;
    }
    if (typeof options.technicalImpact === "string") {
      this.technicalImpact =
        (Object.values(TechnicalImpactLevel).find(
          (v) => v === options.technicalImpact,
        ) as TechnicalImpactLevel) || undefined;
    } else {
      this.technicalImpact = options.technicalImpact;
    }
    if (typeof options.publicSafetyImpact === "string") {
      this.publicSafetyImpact =
        (Object.values(PublicSafetyImpactLevel).find(
          (v) => v === options.publicSafetyImpact,
        ) as PublicSafetyImpactLevel) || undefined;
    } else {
      this.publicSafetyImpact = options.publicSafetyImpact;
    }

    // Always try to evaluate if we have the minimum required parameters
    if (
      this.exploitation !== undefined &&
      this.utility !== undefined &&
      this.technicalImpact !== undefined &&
      this.publicSafetyImpact !== undefined
    ) {
      this.outcome = this.evaluate();
    }
  }

  evaluate(): OutcomeSupplier {
    const action = this.traverseTree();
    this.outcome = new OutcomeSupplier(action);
    return this.outcome;
  }

  toVector(): string {
    if (!this.outcome) {
      this.evaluate();
    }

    const exploitationVector =
      { none: "N", public_poc: "P", active: "A" }[
        this.exploitation?.toString?.()?.toUpperCase?.() ?? ""
      ] ||
      this.exploitation ||
      "";
    const utilityVector =
      { laborious: "L", efficient: "E", super_effective: "S" }[
        this.utility?.toString?.()?.toUpperCase?.() ?? ""
      ] ||
      this.utility ||
      "";
    const technical_impactVector =
      { partial: "P", total: "T" }[
        this.technicalImpact?.toString?.()?.toUpperCase?.() ?? ""
      ] ||
      this.technicalImpact ||
      "";
    const public_safetyVector =
      { minimal: "M", significant: "S" }[
        this.publicSafetyImpact?.toString?.()?.toUpperCase?.() ?? ""
      ] ||
      this.publicSafetyImpact ||
      "";
    const timestamp = new Date().toISOString();
    return `SUPPLIERv1/E:${exploitationVector}/U:${utilityVector}/T:${technical_impactVector}/P:${public_safetyVector}/${timestamp}/`;
  }

  static fromVector(vectorString: string): DecisionSupplier {
    const regex = /^SUPPLIERv1\/(.+)\/([0-9T:\-\.Z]+)\/?$/;
    const match = vectorString.match(regex);

    if (!match) {
      throw new Error(
        `Invalid vector string format for Supplier: ${vectorString}`,
      );
    }

    const paramsString = match[1];
    const params = new Map<string, string>();

    const paramPairs = paramsString.split("/");
    for (const pair of paramPairs) {
      const [key, value] = pair.split(":");
      if (key && value !== undefined) {
        params.set(key, value);
      }
    }

    const exploitationMatch = params.get("E");
    const utilityMatch = params.get("U");
    const technical_impactMatch = params.get("T");
    const public_safetyMatch = params.get("P");

    return new DecisionSupplier({
      exploitation:
        { N: "none", P: "public_poc", A: "active" }[exploitationMatch || ""] ||
        exploitationMatch,
      utility:
        { L: "laborious", E: "efficient", S: "super_effective" }[
          utilityMatch || ""
        ] || utilityMatch,
      technicalImpact:
        { P: "partial", T: "total" }[technical_impactMatch || ""] ||
        technical_impactMatch,
      publicSafetyImpact:
        { M: "minimal", S: "significant" }[public_safetyMatch || ""] ||
        public_safetyMatch,
    });
  }

  private traverseTree(): any {
    // Traverse the decision tree to determine the outcome
    if (this.exploitation === ExploitationStatus.none) {
      if (this.utility === UtilityLevel.laborious) {
        if (this.technicalImpact === TechnicalImpactLevel.partial) {
          if (this.publicSafetyImpact === PublicSafetyImpactLevel.minimal) {
            return ActionType.defer;
          } else if (
            this.publicSafetyImpact === PublicSafetyImpactLevel.significant
          ) {
            return ActionType.scheduled;
          }
        } else if (this.technicalImpact === TechnicalImpactLevel.total) {
          if (this.publicSafetyImpact === PublicSafetyImpactLevel.minimal) {
            return ActionType.defer;
          } else if (
            this.publicSafetyImpact === PublicSafetyImpactLevel.significant
          ) {
            return ActionType.scheduled;
          }
        }
      } else if (this.utility === UtilityLevel.efficient) {
        if (this.technicalImpact === TechnicalImpactLevel.partial) {
          if (this.publicSafetyImpact === PublicSafetyImpactLevel.minimal) {
            return ActionType.defer;
          } else if (
            this.publicSafetyImpact === PublicSafetyImpactLevel.significant
          ) {
            return ActionType.scheduled;
          }
        } else if (this.technicalImpact === TechnicalImpactLevel.total) {
          if (this.publicSafetyImpact === PublicSafetyImpactLevel.minimal) {
            return ActionType.scheduled;
          } else if (
            this.publicSafetyImpact === PublicSafetyImpactLevel.significant
          ) {
            return ActionType.scheduled;
          }
        }
      } else if (this.utility === UtilityLevel.super_effective) {
        if (this.technicalImpact === TechnicalImpactLevel.partial) {
          if (this.publicSafetyImpact === PublicSafetyImpactLevel.minimal) {
            return ActionType.defer;
          } else if (
            this.publicSafetyImpact === PublicSafetyImpactLevel.significant
          ) {
            return ActionType.scheduled;
          }
        } else if (this.technicalImpact === TechnicalImpactLevel.total) {
          if (this.publicSafetyImpact === PublicSafetyImpactLevel.minimal) {
            return ActionType.scheduled;
          } else if (
            this.publicSafetyImpact === PublicSafetyImpactLevel.significant
          ) {
            return ActionType.out_of_cycle;
          }
        }
      }
    } else if (this.exploitation === ExploitationStatus.public_poc) {
      if (this.utility === UtilityLevel.laborious) {
        if (this.technicalImpact === TechnicalImpactLevel.partial) {
          if (this.publicSafetyImpact === PublicSafetyImpactLevel.minimal) {
            return ActionType.defer;
          } else if (
            this.publicSafetyImpact === PublicSafetyImpactLevel.significant
          ) {
            return ActionType.scheduled;
          }
        } else if (this.technicalImpact === TechnicalImpactLevel.total) {
          if (this.publicSafetyImpact === PublicSafetyImpactLevel.minimal) {
            return ActionType.scheduled;
          } else if (
            this.publicSafetyImpact === PublicSafetyImpactLevel.significant
          ) {
            return ActionType.out_of_cycle;
          }
        }
      } else if (this.utility === UtilityLevel.efficient) {
        if (this.technicalImpact === TechnicalImpactLevel.partial) {
          if (this.publicSafetyImpact === PublicSafetyImpactLevel.minimal) {
            return ActionType.scheduled;
          } else if (
            this.publicSafetyImpact === PublicSafetyImpactLevel.significant
          ) {
            return ActionType.out_of_cycle;
          }
        } else if (this.technicalImpact === TechnicalImpactLevel.total) {
          if (this.publicSafetyImpact === PublicSafetyImpactLevel.minimal) {
            return ActionType.scheduled;
          } else if (
            this.publicSafetyImpact === PublicSafetyImpactLevel.significant
          ) {
            return ActionType.out_of_cycle;
          }
        }
      } else if (this.utility === UtilityLevel.super_effective) {
        if (this.technicalImpact === TechnicalImpactLevel.partial) {
          if (this.publicSafetyImpact === PublicSafetyImpactLevel.minimal) {
            return ActionType.scheduled;
          } else if (
            this.publicSafetyImpact === PublicSafetyImpactLevel.significant
          ) {
            return ActionType.out_of_cycle;
          }
        } else if (this.technicalImpact === TechnicalImpactLevel.total) {
          if (this.publicSafetyImpact === PublicSafetyImpactLevel.minimal) {
            return ActionType.out_of_cycle;
          } else if (
            this.publicSafetyImpact === PublicSafetyImpactLevel.significant
          ) {
            return ActionType.immediate;
          }
        }
      }
    } else if (this.exploitation === ExploitationStatus.active) {
      if (this.utility === UtilityLevel.laborious) {
        if (this.technicalImpact === TechnicalImpactLevel.partial) {
          if (this.publicSafetyImpact === PublicSafetyImpactLevel.minimal) {
            return ActionType.scheduled;
          } else if (
            this.publicSafetyImpact === PublicSafetyImpactLevel.significant
          ) {
            return ActionType.out_of_cycle;
          }
        } else if (this.technicalImpact === TechnicalImpactLevel.total) {
          if (this.publicSafetyImpact === PublicSafetyImpactLevel.minimal) {
            return ActionType.out_of_cycle;
          } else if (
            this.publicSafetyImpact === PublicSafetyImpactLevel.significant
          ) {
            return ActionType.immediate;
          }
        }
      } else if (this.utility === UtilityLevel.efficient) {
        if (this.technicalImpact === TechnicalImpactLevel.partial) {
          if (this.publicSafetyImpact === PublicSafetyImpactLevel.minimal) {
            return ActionType.out_of_cycle;
          } else if (
            this.publicSafetyImpact === PublicSafetyImpactLevel.significant
          ) {
            return ActionType.immediate;
          }
        } else if (this.technicalImpact === TechnicalImpactLevel.total) {
          if (this.publicSafetyImpact === PublicSafetyImpactLevel.minimal) {
            return ActionType.out_of_cycle;
          } else if (
            this.publicSafetyImpact === PublicSafetyImpactLevel.significant
          ) {
            return ActionType.immediate;
          }
        }
      } else if (this.utility === UtilityLevel.super_effective) {
        if (this.technicalImpact === TechnicalImpactLevel.partial) {
          if (this.publicSafetyImpact === PublicSafetyImpactLevel.minimal) {
            return ActionType.out_of_cycle;
          } else if (
            this.publicSafetyImpact === PublicSafetyImpactLevel.significant
          ) {
            return ActionType.immediate;
          }
        } else if (this.technicalImpact === TechnicalImpactLevel.total) {
          if (this.publicSafetyImpact === PublicSafetyImpactLevel.minimal) {
            return ActionType.immediate;
          } else if (
            this.publicSafetyImpact === PublicSafetyImpactLevel.significant
          ) {
            return ActionType.immediate;
          }
        }
      }
    }

    // Default action for unmapped paths
    return ActionType.defer;
  }
}
